# Generated by Django 5.2.4 on 2025-09-26 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İlan Kategorisi',
                'verbose_name_plural': 'İlan Kategorileri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='HayvanProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hayvan_adi', models.CharField(max_length=100, verbose_name='Hayvan Adı')),
                ('tur', models.CharField(choices=[('KOPEK', 'Köpek'), ('KEDI', 'Kedi'), ('KUS', 'Kuş'), ('DIGER', 'Diğer')], max_length=20, verbose_name='Tür')),
                ('irk', models.CharField(max_length=100, verbose_name='Irk')),
                ('yas', models.CharField(max_length=50, verbose_name='Yaş')),
                ('cinsiyet', models.CharField(choices=[('ERKEK', 'Erkek'), ('DISI', 'Dişi'), ('BILINMIYOR', 'Bilinmiyor')], max_length=20, verbose_name='Cinsiyet')),
                ('asi_durumu', models.BooleanField(choices=[(True, 'Var'), (False, 'Yok')], default=False, verbose_name='Aşı Durumu')),
                ('ic_parazit', models.BooleanField(choices=[(True, 'Var'), (False, 'Yok')], default=False, verbose_name='İç Parazit')),
                ('dis_parazit', models.BooleanField(choices=[(True, 'Var'), (False, 'Yok')], default=False, verbose_name='Dış Parazit')),
                ('kredi_karti_odeme', models.BooleanField(choices=[(True, 'Var'), (False, 'Yok')], default=False, verbose_name='Kredi Kartına Ödeme')),
                ('sehir_disi_gonderim', models.BooleanField(choices=[(True, 'Var'), (False, 'Yok')], default=False, verbose_name='Şehir Dışına Gönderim')),
                ('il', models.CharField(max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(max_length=50, verbose_name='İlçe')),
                ('mahalle', models.CharField(blank=True, max_length=100, verbose_name='Mahalle')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='hayvan_profilleri/', verbose_name='Profil Fotoğrafı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hayvan_profilleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hayvan Profili',
                'verbose_name_plural': 'Hayvan Profilleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='HayvanResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='hayvan_resimleri/', verbose_name='Resim')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hayvan_profili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='ilan.hayvanprofili')),
            ],
            options={
                'verbose_name': 'Hayvan Resmi',
                'verbose_name_plural': 'Hayvan Resimleri',
                'ordering': ['sira', 'olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('ilan_turu', models.CharField(choices=[('SAHIPLENDIRME', 'Sahiplendirme'), ('SATIS', 'Satış'), ('KAYIP', 'Kayıp'), ('BULUNTU', 'Buluntu')], max_length=20, verbose_name='İlan Türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (TL)')),
                ('onemli_mi', models.BooleanField(default=False, verbose_name='Öne Çıkarılsın mı?')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('onaylandi', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('bitis_tarihi', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('goruntulenme_sayisi', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('favori_sayisi', models.PositiveIntegerField(default=0, verbose_name='Favori Sayısı')),
                ('hayvan_profili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='ilan.hayvanprofili')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-onemli_mi', '-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KrediHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_turu', models.CharField(choices=[('PROFIL_OLUSTURMA', 'Profil Oluşturma'), ('ILAN_VERME', 'İlan Verme'), ('ONEMLI_ILAN', 'Önemli İlan'), ('BAKIYE_EKLEME', 'Bakiye Ekleme')], max_length=20, verbose_name='Hareket Türü')),
                ('miktar', models.IntegerField(verbose_name='Miktar')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('hayvan_profili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ilan.hayvanprofili')),
                ('ilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ilan.ilan')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kredi_hareketleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kredi Hareketi',
                'verbose_name_plural': 'Kredi Hareketleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
