# Generated by Django 5.2.4 on 2025-09-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0001_initial'),
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hayvanprofili',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hayvan_profilleri', to='anahtarlik.il', verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='hayvanprofili',
            name='ilce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hayvan_profilleri', to='anahtarlik.ilce', verbose_name='İlçe'),
        ),
    ]
