# Generated by Django 5.2.4 on 2025-09-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0001_initial'),
        ('ilan', '0002_alter_hayvanprofili_il_alter_hayvanprofili_ilce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hayvanprofili',
            name='irk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hayvan_profilleri', to='anahtarlik.irk', verbose_name='Irk'),
        ),
        migrations.AlterField(
            model_name='hayvanprofili',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hayvan_profilleri', to='anahtarlik.tur', verbose_name='Tür'),
        ),
    ]
