# Generated by Django 5.2.4 on 2025-10-12 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0005_etiketkategorifotografi'),
        ('ilan', '0003_alter_hayvanprofili_irk_alter_hayvanprofili_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredihareketi',
            name='etiket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiket.etiket'),
        ),
        migrations.AlterField(
            model_name='kredihareketi',
            name='hareket_turu',
            field=models.CharField(choices=[('PROFIL_OLUSTURMA', 'Profil Oluşturma'), ('ILAN_VERME', 'İlan Verme'), ('ONEMLI_ILAN', 'Önemli İlan'), ('BAKIYE_EKLEME', 'Bakiye Ekleme'), ('ETIKET_SATIS', 'Etiket Satışı'), ('ETIKET_AKTIVASYON', 'Etiket Aktivasyonu')], max_length=20, verbose_name='Hareket Türü'),
        ),
    ]
