# Generated by Django 5.2.4 on 2025-10-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0004_kredihareketi_etiket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrediPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kredi_adet', models.IntegerField(verbose_name='Kredi Adedi')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('one_cikan', models.BooleanField(default=False, verbose_name='Öne Çıkan Paket')),
                ('etiket', models.CharField(blank=True, help_text="Örn: 'En Popüler', 'En Avantajlı'", max_length=50, verbose_name='Etiket')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Kredi Paketi',
                'verbose_name_plural': 'Kredi Paketleri',
                'ordering': ['sira', 'fiyat'],
            },
        ),
    ]
