# Generated by Django 5.2.4 on 2025-10-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0005_kredipaketi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kredihareketi',
            name='hareket_turu',
            field=models.CharField(choices=[('PROFIL_OLUSTURMA', 'Profil Oluşturma'), ('ILAN_VERME', 'İlan Verme'), ('ONEMLI_ILAN', 'Önemli İlan'), ('BAKIYE_EKLEME', 'Bakiye Ekleme'), ('ETIKET_SATIS', 'Etiket Satışı'), ('ETIKET_AKTIVASYON', 'Etiket Aktivasyonu'), ('SATIN_ALMA', 'Kredi Satın Alma')], max_length=20, verbose_name='Hareket Türü'),
        ),
    ]
