# Generated by Django 5.2.4 on 2025-10-24 08:00

import django.db.models.deletion
from django.db import migrations, models


def clear_old_mahalle_data(apps, schema_editor):
    """Eski CharField mahalle verilerini temizle"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Eski mahalle CharField verilerini NULL yap
        cursor.execute("UPDATE ilan_hayvanprofili SET mahalle = NULL WHERE mahalle IS NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0011_kullaniciadresi_mahalle_diger_sahip_mahalle_diger'),
        ('ilan', '0006_alter_kredihareketi_hareket_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hayvanprofili',
            name='mahalle_diger',
            field=models.CharField(blank=True, help_text='Mahalle listede yoksa buraya yazınız', max_length=200, verbose_name='Mahalle (Manuel)'),
        ),
        # Önce mahalle field'ını nullable CharField yap
        migrations.AlterField(
            model_name='hayvanprofili',
            name='mahalle',
            field=models.CharField(max_length=100, verbose_name='Mahalle', blank=True, null=True),
        ),
        # CharField verilerini temizle
        migrations.RunPython(clear_old_mahalle_data, reverse_code=migrations.RunPython.noop),
        # Sonra ForeignKey'e çevir
        migrations.AlterField(
            model_name='hayvanprofili',
            name='mahalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hayvan_profilleri', to='anahtarlik.mahalle', verbose_name='Mahalle'),
        ),
    ]
