# Generated by Django 5.2.4 on 2025-10-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0007_hayvanprofili_mahalle_diger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hayvanprofili',
            name='kredi_karti_odeme',
        ),
    ]
