# Generated by Django 5.2.4 on 2025-10-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0008_remove_hayvanprofili_kredi_karti_odeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_adi', models.CharField(help_text='Örn: Temel Paket, Premium Paket', max_length=100, verbose_name='Paket Adı')),
                ('aciklama', models.TextField(blank=True, help_text='Paket hakkında kısa açıklama', verbose_name='Açıklama')),
                ('ilan_sayisi', models.IntegerField(help_text='Bu paket kaç ilan hakkı veriyor?', verbose_name='İlan Sayısı')),
                ('toplam_kredi', models.IntegerField(help_text='Pakette toplam kaç kredi var?', verbose_name='Toplam Kredi')),
                ('tasarruf_kredi', models.IntegerField(default=0, help_text='Tek tek alınması durumunda kazanılan kredi', verbose_name='Tasarruf Kredi')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('ilan_basi_kredi', models.IntegerField(default=150, help_text='Standart ilan verme maliyeti', verbose_name='İlan Başı Kredi')),
                ('onemli_ilan_ek_ucret', models.IntegerField(default=50, help_text='Öne çıkarmak için ek kredi', verbose_name='Önemli İlan Ek Ücret')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('one_cikan', models.BooleanField(default=False, verbose_name='Öne Çıkan Paket')),
                ('etiket', models.CharField(blank=True, help_text="Örn: 'EN POPÜLER', '%20 İNDİRİM'", max_length=50, verbose_name='Özel Etiket')),
                ('renk', models.CharField(default='#5B9BD5', help_text='Paket kartı için renk kodu', max_length=20, verbose_name='Renk Kodu')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'İlan Paketi',
                'verbose_name_plural': 'İlan Paketleri',
                'ordering': ['sira', 'fiyat'],
            },
        ),
    ]
