# Generated by Django 5.2.4 on 2025-10-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0009_ilanpaketi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IlanPaketi',
        ),
    ]
