# Generated by Django 5.2.4 on 2025-10-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0010_delete_ilanpaketi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilan',
            name='fiyat',
        ),
    ]
