# Generated by Django 5.2.4 on 2025-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0011_remove_ilan_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (TL)'),
        ),
    ]
