# Generated by Django 5.2.4 on 2025-11-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0018_enforce_evcilhayvan_fk'),
        ('ilan', '0012_ilan_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hayvanprofili',
            name='evcil_hayvan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hayvan_profilleri', to='anahtarlik.evcilhayvan', verbose_name='Evcil Hayvan'),
        ),
    ]
