# Generated by Django 5.2.4 on 2025-11-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0013_hayvanprofili_evcil_hayvan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hayvanprofili',
            name='yas',
        ),
        migrations.AddField(
            model_name='hayvanprofili',
            name='dogum_tarihi',
            field=models.DateField(blank=True, help_text='Hayvanın doğum tarihi', null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
