# Generated by Django 5.2.4 on 2025-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0017_hayvanprofili_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hayvanprofili',
            name='telefon',
            field=models.CharField(help_text='İlan için iletişim telefon numarası (05XX XXX XX XX formatında)', max_length=15, verbose_name='Telefon Numarası'),
        ),
    ]
