# Generated by Django 5.2.4 on 2025-10-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0007_remove_etikettarama_etiket_etik_tarama__ac7b3e_idx_and_more'),
        ('shop', '0005_alter_urun_tavsiye_edilen_tur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ['-olusturulma_tarihi'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='urun',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='urun',
            name='etiket_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiket.etiketkategori', verbose_name='Etiket Kategorisi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='etiket_ozellikler',
            field=models.JSONField(blank=True, default=dict, verbose_name='Etiket Özellikleri'),
        ),
        migrations.AddField(
            model_name='urun',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='hayvan_turu',
            field=models.CharField(blank=True, help_text='Örn: Kedi, Köpek, Kuş, Balık', max_length=50, null=True, verbose_name='Hayvan Türü'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kullanim_suresi',
            field=models.IntegerField(default=365, help_text='Gün cinsinden', verbose_name='Kullanım Süresi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='qr_kod_ornegi',
            field=models.ImageField(blank=True, null=True, upload_to='etiket_ornekleri/', verbose_name='QR Kod Örneği'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_tipi',
            field=models.CharField(choices=[('normal', 'Normal Ürün (Petshop)'), ('etiket', 'Etiket Ürünü')], default='normal', max_length=20, verbose_name='Ürün Tipi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kategori', verbose_name='Petshop Kategorisi'),
        ),
    ]
