# Generated by Django 5.2.4 on 2025-10-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_urun_options_urun_aktif_urun_etiket_kategori_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='kategori',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='kategori',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.kategori'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='sira',
            field=models.IntegerField(default=0, help_text='Kategori sıralaması'),
        ),
        migrations.AddField(
            model_name='urun',
            name='agirlik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ağırlık (kg)'),
        ),
        migrations.AddField(
            model_name='urun',
            name='anahtar_kelimeler',
            field=models.TextField(blank=True, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='urun',
            name='begeni_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Beğeni Sayısı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='boyut',
            field=models.CharField(blank=True, max_length=50, verbose_name='Boyut'),
        ),
        migrations.AddField(
            model_name='urun',
            name='goruntulenme_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='indirimli',
            field=models.BooleanField(default=False, verbose_name='İndirimli'),
        ),
        migrations.AddField(
            model_name='urun',
            name='marka',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='urun',
            name='meta_aciklama',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='urun',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='urun',
            name='one_cikan',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan'),
        ),
        migrations.AddField(
            model_name='urun',
            name='ozellikler',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ürün Özellikleri'),
        ),
        migrations.AddField(
            model_name='urun',
            name='renk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='urun',
            name='satis_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Satış Sayısı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='yas_araligi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yaş Aralığı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='yeni_urun',
            field=models.BooleanField(default=False, verbose_name='Yeni Ürün'),
        ),
    ]
