# Generated by Django 5.2.4 on 2025-10-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_kategori_options_kategori_aciklama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazaKarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('alt_baslik', models.CharField(blank=True, max_length=300, verbose_name='Alt Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('resim_url', models.URLField(help_text='Unsplash veya başka bir kaynak', verbose_name='Resim URL')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='magaza_kartlari/', verbose_name='Resim (Upload)')),
                ('link_url', models.CharField(blank=True, help_text='Örn: /shop/etiket/ veya #', max_length=200, verbose_name='Link URL')),
                ('buton_metni', models.CharField(default='Ürünleri İncele', max_length=100, verbose_name='Buton Metni')),
                ('icon', models.CharField(default='🛍️', max_length=50, verbose_name='Icon (Emoji)')),
                ('renk', models.CharField(default='#667eea', help_text='Hex renk kodu', max_length=50, verbose_name='Renk Kodu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, help_text='Küçük sayı önce gösterilir', verbose_name='Sıra')),
                ('urun_sayisi', models.IntegerField(default=0, verbose_name='Ürün Sayısı (Manuel)')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mağaza Kartı',
                'verbose_name_plural': 'Mağaza Kartları',
                'ordering': ['sira', 'baslik'],
            },
        ),
    ]
