# Generated by Django 5.2.4 on 2025-10-23 07:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_magazakarti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KargoFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='kargo_logolar/')),
                ('sabit_ucret', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sabit Ücret')),
                ('ucretsiz_kargo_limiti', models.DecimalField(blank=True, decimal_places=2, help_text='Bu tutarın üzerinde ücretsiz kargo', max_digits=10, null=True, verbose_name='Ücretsiz Kargo Limiti')),
                ('tahmini_sure_gun', models.IntegerField(default=3, verbose_name='Tahmini Teslimat (Gün)')),
                ('aktif', models.BooleanField(default=True)),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kargo Firması',
                'verbose_name_plural': 'Kargo Firmaları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kupon Kodu')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('kupon_tipi', models.CharField(choices=[('yuzde', 'Yüzde İndirim'), ('tutar', 'Tutar İndirim'), ('ucretsiz_kargo', 'Ücretsiz Kargo')], default='yuzde', max_length=20)),
                ('indirim_degeri', models.DecimalField(decimal_places=2, help_text='Yüzde için 1-100 arası, Tutar için TL', max_digits=10, verbose_name='İndirim Değeri')),
                ('minimum_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Sipariş Tutarı')),
                ('maksimum_indirim', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum İndirim Tutarı')),
                ('kullanim_limiti', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Kullanım Limiti')),
                ('kullanici_basina_limit', models.PositiveIntegerField(default=1, verbose_name='Kullanıcı Başına Limit')),
                ('kullanim_sayisi', models.PositiveIntegerField(default=0)),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('aktif', models.BooleanField(default=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Örn: Ev Adresim', max_length=100, verbose_name='Adres Başlığı')),
                ('adres_tipi', models.CharField(choices=[('ev', 'Ev'), ('is', 'İş'), ('diger', 'Diğer')], default='ev', max_length=20)),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('il', models.CharField(max_length=100, verbose_name='İl')),
                ('ilce', models.CharField(max_length=100, verbose_name='İlçe')),
                ('mahalle', models.CharField(max_length=200, verbose_name='Mahalle')),
                ('adres_satiri', models.TextField(verbose_name='Adres')),
                ('posta_kodu', models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu')),
                ('adres_tarifi', models.TextField(blank=True, help_text='Kolay bulmak için', verbose_name='Adres Tarifi')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan Adres')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ['-varsayilan', '-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KuponKullanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kullanim_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kupon')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.siparis')),
            ],
            options={
                'verbose_name': 'Kupon Kullanımı',
                'verbose_name_plural': 'Kupon Kullanımları',
            },
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sepet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'Sepetler',
            },
        ),
        migrations.CreateModel(
            name='SiparisDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekliyor', 'Ödeme Bekleniyor'), ('odendi', 'Ödeme Alındı'), ('hazirlaniyor', 'Hazırlanıyor'), ('kargoda', 'Kargoya Verildi'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal Edildi'), ('iade', 'İade Edildi')], max_length=20)),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durum_gecmisi', to='shop.siparis')),
            ],
            options={
                'verbose_name': 'Sipariş Durumu',
                'verbose_name_plural': 'Sipariş Durumları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='UrunVaryant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varyant_tipi', models.CharField(choices=[('beden', 'Beden'), ('renk', 'Renk'), ('boyut', 'Boyut'), ('agirlik', 'Ağırlık')], default='beden', max_length=20)),
                ('deger', models.CharField(help_text='Örn: S, Kırmızı, 2kg', max_length=100, verbose_name='Değer')),
                ('stok', models.IntegerField(default=0, verbose_name='Stok Adedi')),
                ('fiyat_farki', models.DecimalField(decimal_places=2, default=0, help_text='Ana fiyata eklenecek/çıkarılacak tutar', max_digits=10, verbose_name='Fiyat Farkı')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Stok Kodu')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='varyant_resimleri/')),
                ('aktif', models.BooleanField(default=True)),
                ('sira', models.IntegerField(default=0, help_text='Gösterim sırası')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varyantlar', to='shop.urun')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'ordering': ['sira', 'deger'],
                'unique_together': {('urun', 'varyant_tipi', 'deger')},
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriler', to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.urun')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoriler',
                'ordering': ['-ekleme_tarihi'],
                'unique_together': {('kullanici', 'urun')},
            },
        ),
        migrations.CreateModel(
            name='SepetKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(default=1)),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='shop.sepet')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.urun')),
                ('varyant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.urunvaryant')),
            ],
            options={
                'verbose_name': 'Sepet Kalemi',
                'verbose_name_plural': 'Sepet Kalemleri',
                'unique_together': {('sepet', 'urun', 'varyant')},
            },
        ),
        migrations.CreateModel(
            name='UrunYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yildiz', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Yıldız (1-5)')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('yorum', models.TextField(verbose_name='Yorum')),
                ('resim1', models.ImageField(blank=True, null=True, upload_to='yorum_resimleri/')),
                ('resim2', models.ImageField(blank=True, null=True, upload_to='yorum_resimleri/')),
                ('resim3', models.ImageField(blank=True, null=True, upload_to='yorum_resimleri/')),
                ('dogrulanmis_alisveris', models.BooleanField(default=False, verbose_name='Doğrulanmış Alışveriş')),
                ('faydali_sayisi', models.PositiveIntegerField(default=0)),
                ('onaylandi', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='shop.urun')),
            ],
            options={
                'verbose_name': 'Ürün Yorumu',
                'verbose_name_plural': 'Ürün Yorumları',
                'ordering': ['-olusturulma_tarihi'],
                'unique_together': {('urun', 'kullanici')},
            },
        ),
    ]
