# Generated by Django 5.2.4 on 2025-10-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_kargofirma_kupon_adres_kuponkullanim_sepet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazaKartiResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='magaza_kartlari/slider/', verbose_name='Resim')),
                ('sira', models.IntegerField(default=0, help_text='Küçük sayı önce gösterilir', verbose_name='Sıra')),
                ('alt_metin', models.CharField(blank=True, help_text='Resim altında gösterilecek metin', max_length=200, verbose_name='Alt Metin')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('magaza_karti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kart_resimleri', to='shop.magazakarti', verbose_name='Mağaza Kartı')),
            ],
            options={
                'verbose_name': 'Mağaza Kartı Resmi',
                'verbose_name_plural': 'Mağaza Kartı Resimleri',
                'ordering': ['sira', 'olusturulma_tarihi'],
            },
        ),
    ]
