# Generated by Django 5.2.4 on 2025-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_magazakartiresim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='kategori',
        ),
        migrations.AddField(
            model_name='urun',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, related_name='urunler', to='shop.kategori', verbose_name='Petshop Kategorileri'),
        ),
    ]
