# Generated by Django 5.2.4 on 2025-10-23 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0009_kullaniciadresi'),
        ('shop', '0011_remove_urun_kategori_urun_kategoriler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='misafir_ad_soyad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Misafir Ad Soyad'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='misafir_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Misafir Email'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='misafir_telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Misafir Telefon'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_adresleri', to='anahtarlik.il', verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='ilce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_adresleri', to='anahtarlik.ilce', verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='kullanici',
            field=models.ForeignKey(blank=True, help_text='Misafir siparişler için boş bırakılabilir', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
