# Generated by Django 5.2.4 on 2025-10-23 20:41

from django.db import migrations, models
import django.db.models.deletion


def convert_adres_data(apps, schema_editor):
    """
    Mevcut CharField il/ilce verilerini ForeignKey'e dönüştür
    """
    Adres = apps.get_model('shop', 'Adres')
    Il = apps.get_model('anahtarlik', 'Il')
    Ilce = apps.get_model('anahtarlik', 'Ilce')

    # Mevcut adresleri işle
    for adres in Adres.objects.all():
        if adres.il_old and adres.ilce_old:
            # İl'i bul veya oluştur
            il_obj, _ = Il.objects.get_or_create(ad=adres.il_old.strip())

            # İlçe'yi bul veya oluştur
            ilce_obj, _ = Ilce.objects.get_or_create(
                il=il_obj,
                ad=adres.ilce_old.strip()
            )

            # Yeni ForeignKey alanlarını doldur
            adres.il_new = il_obj
            adres.ilce_new = ilce_obj
            adres.save(update_fields=['il_new', 'ilce_new'])


def reverse_convert_adres_data(apps, schema_editor):
    """
    Geri alma işlemi - ForeignKey'den CharField'a
    """
    Adres = apps.get_model('shop', 'Adres')

    for adres in Adres.objects.all():
        if adres.il_new and adres.ilce_new:
            adres.il_old = adres.il_new.ad
            adres.ilce_old = adres.ilce_new.ad
            adres.save(update_fields=['il_old', 'ilce_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_siparis_misafir_ad_soyad_siparis_misafir_email_and_more'),
        ('anahtarlik', '0009_kullaniciadresi'),
    ]

    operations = [
        # Adım 1: Eski alanları yeniden adlandır
        migrations.RenameField(
            model_name='adres',
            old_name='il',
            new_name='il_old',
        ),
        migrations.RenameField(
            model_name='adres',
            old_name='ilce',
            new_name='ilce_old',
        ),

        # Adım 2: Yeni ForeignKey alanları ekle (nullable)
        migrations.AddField(
            model_name='adres',
            name='il_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shop_adresleri_temp',
                to='anahtarlik.il',
                verbose_name='İl'
            ),
        ),
        migrations.AddField(
            model_name='adres',
            name='ilce_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shop_adresleri_temp',
                to='anahtarlik.ilce',
                verbose_name='İlçe'
            ),
        ),

        # Adım 3: Verileri dönüştür
        migrations.RunPython(convert_adres_data, reverse_convert_adres_data),

        # Adım 4: Eski alanları sil
        migrations.RemoveField(
            model_name='adres',
            name='il_old',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='ilce_old',
        ),

        # Adım 5: Yeni alanları yeniden adlandır
        migrations.RenameField(
            model_name='adres',
            old_name='il_new',
            new_name='il',
        ),
        migrations.RenameField(
            model_name='adres',
            old_name='ilce_new',
            new_name='ilce',
        ),

        # Adım 6: NOT NULL constraint ekle
        migrations.AlterField(
            model_name='adres',
            name='il',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shop_adresleri',
                to='anahtarlik.il',
                verbose_name='İl'
            ),
        ),
        migrations.AlterField(
            model_name='adres',
            name='ilce',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shop_adresleri',
                to='anahtarlik.ilce',
                verbose_name='İlçe'
            ),
        ),
    ]
