# Generated by Django 5.2.4 on 2025-10-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0010_alter_ilce_options_mahalle_kullaniciadresi_mahalle_and_more'),
        ('shop', '0013_convert_adres_il_ilce_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='mahalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_adresleri', to='anahtarlik.mahalle', verbose_name='Mahalle'),
        ),
    ]
