# Generated by Django 5.2.4 on 2025-10-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_adres_mahalle_diger_alter_adres_mahalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='kargo_firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kargofirma', verbose_name='Kargo Firması'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='kargo_takip_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kargo Takip No'),
        ),
        migrations.AddField(
            model_name='siparisdurum',
            name='kargo_takip_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kargo Takip No'),
        ),
    ]









