# Generated by Django 5.2.4 on 2025-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_add_kargo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='petshop_veteriner_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boş bırakılırsa normal müşteri fiyatı kullanılır', max_digits=10, null=True, verbose_name='Petshop/Veteriner Fiyatı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='petshop_veteriner_fiyat_aktif',
            field=models.BooleanField(default=False, help_text='Aktif edilirse petshop ve veteriner kullanıcıları için özel fiyat gösterilir', verbose_name='Bayi Fiyatını Kullan'),
        ),
        migrations.AddField(
            model_name='urun',
            name='petshop_veteriner_indirimli_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Petshop/Veteriner İndirimli Fiyat'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Normal Müşteri Fiyatı'),
        ),
    ]
