# Generated by Django 5.2.4 on 2025-10-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_urun_petshop_veteriner_fiyat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazakarti',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='magazakarti',
            name='resim',
        ),
        migrations.RemoveField(
            model_name='magazakarti',
            name='resim_url',
        ),
        migrations.RemoveField(
            model_name='magazakarti',
            name='urun_sayisi',
        ),
        migrations.DeleteModel(
            name='MagazaKartiResim',
        ),
    ]
