# Generated by Django 5.2.4 on 2025-10-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_magazakarti_aciklama_remove_magazakarti_resim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazakarti',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='magazakarti',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='magaza_kartlari/', verbose_name='Resim (Upload)'),
        ),
        migrations.AddField(
            model_name='magazakarti',
            name='resim_url',
            field=models.URLField(blank=True, help_text='Unsplash veya başka bir kaynak', null=True, verbose_name='Resim URL'),
        ),
        migrations.AddField(
            model_name='magazakarti',
            name='urun_sayisi',
            field=models.IntegerField(default=0, verbose_name='Ürün Sayısı (Manuel)'),
        ),
        migrations.CreateModel(
            name='MagazaKartiResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='magaza_kartlari/slider/', verbose_name='Resim')),
                ('sira', models.IntegerField(default=0, help_text='Küçük sayı önce gösterilir', verbose_name='Sıra')),
                ('alt_metin', models.CharField(blank=True, help_text='Resim altında gösterilecek metin', max_length=200, verbose_name='Alt Metin')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('magaza_karti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kart_resimleri', to='shop.magazakarti', verbose_name='Mağaza Kartı')),
            ],
            options={
                'verbose_name': 'Mağaza Kartı Resmi',
                'verbose_name_plural': 'Mağaza Kartı Resimleri',
                'ordering': ['sira', 'olusturulma_tarihi'],
            },
        ),
    ]
