# Generated by Django 5.2.4 on 2025-10-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_magazakarti_aciklama_magazakarti_resim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazakarti',
            name='resim',
        ),
        migrations.RemoveField(
            model_name='magazakarti',
            name='resim_url',
        ),
    ]
