# Generated by Django 5.2.4 on 2025-10-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_magazakarti_resim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepetkalemi',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat'),
        ),
    ]
