# Generated by Django 5.2.4 on 2025-10-28 20:40

from django.db import migrations


def update_sepet_kalemi_prices(apps, schema_editor):
    """Mevcut sepet kalemlerinin birim_fiyat alanını güncelle"""
    SepetKalemi = apps.get_model('shop', 'SepetKalemi')
    
    for kalem in SepetKalemi.objects.all():
        if kalem.varyant:
            kalem.birim_fiyat = kalem.varyant.final_fiyat
        else:
            # Basit fiyat hesaplama - indirimli fiyat varsa onu kullan
            if kalem.urun.indirimli_fiyat:
                kalem.birim_fiyat = kalem.urun.indirimli_fiyat
            else:
                kalem.birim_fiyat = kalem.urun.fiyat
        kalem.save()


def reverse_update_sepet_kalemi_prices(apps, schema_editor):
    """Geri alma fonksiyonu - birim_fiyat alanını sıfırla"""
    SepetKalemi = apps.get_model('shop', 'SepetKalemi')
    SepetKalemi.objects.all().update(birim_fiyat=0)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_sepetkalemi_birim_fiyat'),
    ]

    operations = [
        migrations.RunPython(update_sepet_kalemi_prices, reverse_update_sepet_kalemi_prices),
    ]
