# Generated by Django 5.2.4 on 2025-10-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20251028_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kargo_firmasi',
            field=models.ForeignKey(blank=True, help_text='Bu ürün için özel kargo firması seç', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kargofirma', verbose_name='Kargo Firması'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kargo_ozel',
            field=models.BooleanField(default=False, help_text='Bu ürün için özel kargo ayarları kullan', verbose_name='Özel Kargo Ayarları'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kargo_teslimat_suresi',
            field=models.PositiveIntegerField(blank=True, help_text='Bu ürün için özel teslimat süresi (boş bırakılırsa kargo firmasının süresi kullanılır)', null=True, verbose_name='Teslimat Süresi (Gün)'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kargo_ucreti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu ürün için özel kargo ücreti (boş bırakılırsa kargo firmasının sabit ücreti kullanılır)', max_digits=10, null=True, verbose_name='Kargo Ücreti'),
        ),
        migrations.AddField(
            model_name='urun',
            name='ucretsiz_kargo_limiti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu ürün için özel ücretsiz kargo limiti (boş bırakılırsa kargo firmasının limiti kullanılır)', max_digits=10, null=True, verbose_name='Ücretsiz Kargo Limiti'),
        ),
    ]
