# Generated by Django 5.2.4 on 2025-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0018_enforce_evcilhayvan_fk'),
        ('shop', '0023_urun_kargo_firmasi_urun_kargo_ozel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Ödeme Bekleniyor'), ('odendi', 'Ödeme Alındı'), ('hazirlaniyor', 'Hazırlanıyor'), ('kargoda', 'Kargoya Verildi'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal Edildi'), ('iade', 'İade Edildi')], default='bekliyor', max_length=20),
        ),
        migrations.RemoveField(
            model_name='urun',
            name='hayvan_turu',
        ),
        migrations.AddField(
            model_name='urun',
            name='hayvan_turu',
            field=models.ManyToManyField(blank=True, help_text='Ürünün hangi hayvan türleri için uygun olduğunu seçin (birden fazla seçilebilir)', related_name='urunler', to='anahtarlik.tur', verbose_name='Hayvan Türü'),
        ),
    ]
