# Generated by Django 5.2.4 on 2025-11-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0018_enforce_evcilhayvan_fk'),
        ('shop', '0024_change_hayvan_turu_to_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='tavsiye_edilen_tur',
        ),
        migrations.AddField(
            model_name='urun',
            name='tavsiye_edilen_tur',
            field=models.ManyToManyField(blank=True, help_text='Bu ürünün özellikle hangi hayvan türleri için tavsiye edildiğini seçin (birden fazla seçilebilir)', related_name='tavsiye_edilen_urunler', to='anahtarlik.tur', verbose_name='Tavsiye Edilen Hayvan Türü'),
        ),
    ]
