# Generated by Django 4.2.26 on 2025-12-09 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_change_tavsiye_edilen_tur_to_manytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetshopSayfaAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_baslik', models.CharField(default='Pet Ürünleri', help_text='Sayfa üst kısmında görünecek başlık', max_length=200, verbose_name='Sayfa Başlığı')),
                ('sayfa_aciklama', models.TextField(default='Evcil dostlarınız için en kaliteli pet ürünlerini keşfedin', help_text='Sayfa başlığının altında görünecek açıklama metni', verbose_name='Sayfa Açıklaması')),
                ('hero_baslik', models.CharField(default='Pet Ürünleri', help_text="Hero section'da görünecek ana başlık", max_length=200, verbose_name='Hero Başlık')),
                ('hero_aciklama', models.TextField(default='Evcil dostlarınız için en kaliteli ürünleri bulun', help_text="Hero section'da görünecek açıklama metni", verbose_name='Hero Açıklama')),
                ('sayfa_basina_urun', models.IntegerField(default=12, help_text='Bir sayfada gösterilecek ürün sayısı', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Sayfa Başına Ürün Sayısı')),
                ('varsayilan_siralama', models.CharField(choices=[('default', 'Varsayılan (Öne Çıkan, Yeni, İsim)'), ('price_asc', 'Fiyat (Düşükten Yükseğe)'), ('price_desc', 'Fiyat (Yüksekten Düşüğe)'), ('name_asc', 'İsim (A-Z)'), ('name_desc', 'İsim (Z-A)')], default='default', help_text='Kullanıcı sıralama seçmediğinde kullanılacak varsayılan sıralama', max_length=20, verbose_name='Varsayılan Sıralama')),
                ('seo_baslik', models.CharField(blank=True, help_text='SEO için sayfa başlığı (max 70 karakter)', max_length=70, verbose_name='SEO Başlık')),
                ('seo_aciklama', models.CharField(blank=True, help_text='SEO için meta açıklama (max 160 karakter)', max_length=160, verbose_name='SEO Açıklama')),
                ('seo_anahtar_kelimeler', models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler', max_length=255, verbose_name='SEO Anahtar Kelimeler')),
                ('aktif', models.BooleanField(default=True, help_text='Sayfa ayarları aktif mi?', verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Petshop Sayfa Ayarı',
                'verbose_name_plural': 'Petshop Sayfa Ayarları',
            },
        ),
    ]
