# Generated by Django 4.2.26 on 2025-12-09 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_petshopsayfaayar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petshopsayfaayar',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='petshopsayfaayar',
            name='hero_aciklama',
        ),
        migrations.RemoveField(
            model_name='petshopsayfaayar',
            name='hero_baslik',
        ),
        migrations.RemoveField(
            model_name='petshopsayfaayar',
            name='seo_aciklama',
        ),
        migrations.RemoveField(
            model_name='petshopsayfaayar',
            name='seo_anahtar_kelimeler',
        ),
        migrations.RemoveField(
            model_name='petshopsayfaayar',
            name='seo_baslik',
        ),
        migrations.AddField(
            model_name='petshopsayfaayar',
            name='arama_cubugu_goster',
            field=models.BooleanField(default=True, help_text='Üst kısımda arama çubuğunu göster', verbose_name='Arama Çubuğu Göster'),
        ),
        migrations.AddField(
            model_name='petshopsayfaayar',
            name='kategori_sidebar_goster',
            field=models.BooleanField(default=True, help_text='Sol tarafta kategori listesini göster', verbose_name='Kategori Sidebar Göster'),
        ),
        migrations.AlterField(
            model_name='petshopsayfaayar',
            name='sayfa_aciklama',
            field=models.TextField(default='Evcil dostlarınız için en kaliteli pet ürünleri', help_text='Sayfa açıklama metni', verbose_name='Sayfa Açıklaması'),
        ),
        migrations.AlterField(
            model_name='petshopsayfaayar',
            name='sayfa_basina_urun',
            field=models.IntegerField(default=12, help_text='Bir sayfada gösterilecek ürün sayısı', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Sayfa Başına Ürün'),
        ),
        migrations.AlterField(
            model_name='petshopsayfaayar',
            name='sayfa_baslik',
            field=models.CharField(default='Pet Ürünleri', help_text='Petshop sayfasının ana başlığı', max_length=200, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AlterField(
            model_name='petshopsayfaayar',
            name='varsayilan_siralama',
            field=models.CharField(choices=[('default', 'Varsayılan (Öne Çıkan, Yeni, İsim)'), ('price_asc', 'Fiyat (Düşükten Yükseğe)'), ('price_desc', 'Fiyat (Yüksekten Düşüğe)'), ('name_asc', 'İsim (A-Z)'), ('name_desc', 'İsim (Z-A)')], default='default', help_text='Kategori seçilmediğinde varsayılan sıralama', max_length=20, verbose_name='Varsayılan Sıralama'),
        ),
    ]
