"""
Django settings for courseapp project.
Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path
from decouple import config, Csv

# Baz dizin
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY: Environment variables kullan
SECRET_KEY = config('SECRET_KEY', default='django-insecure-$1!qju8gp_pq9!64se@y!n-h!=@f3%xgf(sx9*o43i$696k(4t-DEVELOPMENT-ONLY')

# DEBUG ayarı - PythonAnywhere'de False olmalı
DEBUG = config('DEBUG', default=False, cast=bool)

# PythonAnywhere için ALLOWED_HOSTS
# Ücretsiz hesap için: username.pythonanywhere.com
# Örnek: ALLOWED_HOSTS = ['username.pythonanywhere.com']
# Production'da mutlaka domain adınızı ekleyin!
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

# Site URL (QR linkleri vb. için kullanılıyor)
# PythonAnywhere'de: https://username.pythonanywhere.com
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')

# Uygulamalar
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Proje uygulamaları
    'anahtarlik',
    'core',
    'accaunt',
    'shop',
    'widget_tweaks',
    'petpanel',
    'etiket',
    'veteriner',
    'petshop',
    'ilan',
]

LOGIN_URL = '/accaunt/login/'

# Orta katmanlar
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Profil tamamlama yönlendirmesi (TEK KEZ!)
    'courseapp.middleware.ProfileCompletionMiddleware',
]

# URL ve WSGI
ROOT_URLCONF = 'courseapp.urls'
WSGI_APPLICATION = 'courseapp.wsgi.application'

# Şablonlar
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Proje kökündeki templates klasörü
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Sepet özeti (shop ile entegre)
                'courseapp.context_processors.sepet_ozeti',
                # Kullanıcı panel hedef URL'si (rol bazlı)
                'courseapp.context_processors.user_panel_target',
                # Kullanıcı kredi bakiyesi
                'courseapp.context_processors.kullanici_kredi',
            ],
        },
    },
]

# Veritabanı (SQLite - geliştirici ortamı)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME'  : BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,  # 20 saniye timeout - database locked hatası için
        },
    }
}

# Şifre doğrulama
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Uluslararasılaştırma
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Sayı formatı için İngilizce locale kullan (nokta için)
USE_L10N = False

# Statik ve medya dosyaları
# PythonAnywhere'de static files /static/ altında otomatik serve edilir
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/static/'  # PythonAnywhere'de bu path kullanılır
STATICFILES_DIRS = [BASE_DIR / "static"]

# PythonAnywhere için static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media dosyaları
# PythonAnywhere'de Web app ayarlarında /media/ -> /home/username/courseapp/media/ mapping yapılmalı
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# PythonAnywhere için static ve media dosyaları notları:
# 1. Static files: python manage.py collectstatic çalıştırılmalı
# 2. Media files: Web app ayarlarında /media/ -> /home/username/courseapp/media/ mapping yapılmalı
# 3. Production'da DEBUG=False olduğunda static/media serving Django'da kapatılmalı

# Varsayılan PK tipi
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-posta (Gmail SMTP - Gerçek gönderim)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Stripe ayarları
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='pk_test_51234567890abcdef')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='sk_test_51234567890abcdef')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='whsec_test_1234567890abcdef')
STRIPE_TEST_MODE = config('STRIPE_TEST_MODE', default=True, cast=bool)

# Site ayarları
CONTACT_EMAIL = config('CONTACT_EMAIL', default='info@petsafehub.com')
ADMIN_EMAILS = config('ADMIN_EMAILS', default='admin@petsafehub.com', cast=Csv())

# Loglama
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Logs klasörünü oluştur
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Production güvenlik ayarları
if not DEBUG:
    # PythonAnywhere ücretsiz hesap HTTPS kullanır, bu ayarlar aktif olabilir
    # Ancak bazı ayarlar PythonAnywhere'de sorun çıkarabilir, dikkatli kullanın
    
    # HTTPS zorunlu (PythonAnywhere'de genelde True olmalı)
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)  # PythonAnywhere'de False olabilir
    
    # HSTS ayarları (PythonAnywhere'de genelde sorun çıkarmaz)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)  # PythonAnywhere'de False
    
    # Cookie güvenliği (PythonAnywhere HTTPS kullanır, True olabilir)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    
    # Frame embedding koruması
    X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='SAMEORIGIN')  # PythonAnywhere'de SAMEORIGIN daha uygun
    
    # XSS koruması
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

