# Generated by Django 4.2 on 2025-09-26 16:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petshop', '0001_initial'),
        ('veteriner', '0007_siparisistemi_numune_mi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvcilHayvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('disi', 'Dişi'), ('bilinmiyor', 'Bilinmiyor')], default='bilinmiyor', max_length=20)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('saglik_notu', models.TextField(blank=True)),
                ('beslenme_notu', models.TextField(blank=True)),
                ('genel_not', models.TextField(blank=True)),
                ('davranis_notu', models.TextField(blank=True)),
                ('kayip_durumu', models.BooleanField(default=False)),
                ('kayip_bildirim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('odul_miktari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='evcil_hayvanlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Irk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'İrk',
                'verbose_name_plural': 'Irklar',
                'ordering': ['tur__ad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='BeslenmeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besin_turu', models.CharField(max_length=100)),
                ('tarih', models.DateField()),
                ('miktar', models.CharField(max_length=50)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beslenme_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='AsiTakvimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_turu', models.CharField(max_length=100)),
                ('planlanan_tarih', models.DateField()),
                ('tamamlandi', models.BooleanField(default=False)),
                ('tamamlanma_tarihi', models.DateField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asi_takvimi', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='AmeliyatKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ameliyat_turu', models.CharField(max_length=100)),
                ('tarih', models.DateField()),
                ('veteriner', models.CharField(blank=True, max_length=100)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameliyat_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='Alerji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerji_turu', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('kaydedilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerjiler', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='IlacKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(max_length=100)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('dozaj', models.CharField(blank=True, max_length=50)),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilac_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='anahtarlik.il')),
            ],
            options={
                'ordering': ['il__ad', 'ad'],
                'unique_together': {('il', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='irk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evcil_hayvanlar', to='anahtarlik.irk'),
        ),
        migrations.CreateModel(
            name='KiloKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('tarih', models.DateField()),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kilo_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
            options={
                'verbose_name': 'Kilo Kaydı',
                'verbose_name_plural': 'Kilo Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='SaglikKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_turu', models.CharField(max_length=100)),
                ('asi_tarihi', models.DateField()),
                ('notlar', models.TextField(blank=True)),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saglik_kayitlari', to='anahtarlik.evcilhayvan')),
            ],
        ),
        migrations.CreateModel(
            name='Sahip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=50)),
                ('soyad', models.CharField(blank=True, max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('yedek_telefon', models.CharField(blank=True, max_length=15)),
                ('adres', models.TextField(blank=True)),
                ('acil_durum_kontagi', models.CharField(blank=True, max_length=15)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sahipleri', to='anahtarlik.il')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sahipleri', to='anahtarlik.ilce')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='sahip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evcil_hayvanlar', to='anahtarlik.sahip'),
        ),
        migrations.AddField(
            model_name='irk',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irklari', to='anahtarlik.tur'),
        ),
        migrations.AddField(
            model_name='evcilhayvan',
            name='tur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evcil_hayvanlar', to='anahtarlik.tur'),
        ),
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seri_numarasi', models.CharField(max_length=50, unique=True)),
                ('qr_kod_url', models.URLField(blank=True)),
                ('aktif', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kilitli', models.BooleanField(default=False)),
                ('kanal', models.CharField(choices=[('ONLINE', 'Online'), ('VET', 'Veteriner'), ('SHOP', 'Petshop')], max_length=10)),
                ('tahsis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('first_activated_at', models.DateTimeField(blank=True, null=True)),
                ('aktiflestirme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('aktivasyon_sayisi', models.PositiveIntegerField(default=0)),
                ('aktiflestiren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiflestirdigi_etiketler', to=settings.AUTH_USER_MODEL)),
                ('satici_petshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_etiketler', to='petshop.petshop')),
                ('satici_veteriner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_etiketler', to='veteriner.veteriner')),
                ('evcil_hayvan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.evcilhayvan')),
            ],
            options={
                'constraints': [models.CheckConstraint(check=models.Q(('kanal__isnull', True), models.Q(('kanal', 'VET'), _negated=True), ('satici_veteriner__isnull', False), _connector='OR'), name='etiket_vet_icin_veteriner_zorunlu'), models.CheckConstraint(check=models.Q(('kanal__isnull', True), models.Q(('kanal', 'SHOP'), _negated=True), ('satici_petshop__isnull', False), _connector='OR'), name='etiket_shop_icin_petshop_zorunlu'), models.CheckConstraint(check=models.Q(('kanal__isnull', True), models.Q(('kanal', 'ONLINE'), _negated=True), models.Q(('satici_veteriner__isnull', True), ('satici_petshop__isnull', True)), _connector='OR'), name='etiket_online_icin_partner_bos')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='irk',
            unique_together={('tur', 'ad')},
        ),
    ]
