# Generated by Django 5.2.4 on 2025-09-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahipProPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_adi', models.CharField(max_length=50, verbose_name='Paket Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ilan_hakki', models.IntegerField(default=0, verbose_name='İlan Hakkı')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('sure_gun', models.IntegerField(default=30, verbose_name='Süre (Gün)')),
                ('asi_hatirlatma', models.BooleanField(default=False, verbose_name='Aşı Hatırlatmaları')),
                ('veteriner_randevu', models.BooleanField(default=False, verbose_name='Veteriner Randevu Hatırlatmaları')),
                ('ilac_takibi', models.BooleanField(default=False, verbose_name='İlaç Takibi')),
                ('beslenme_programi', models.BooleanField(default=False, verbose_name='Beslenme Programı')),
                ('finansal_takip', models.BooleanField(default=False, verbose_name='Finansal Takip')),
                ('egitim_programi', models.BooleanField(default=False, verbose_name='Eğitim Programları')),
                ('foto_galeri_limit', models.IntegerField(default=50, verbose_name='Fotoğraf Galeri Limiti')),
                ('renk', models.CharField(default='#007bff', max_length=20, verbose_name='Renk Kodu')),
                ('siralama', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Sahip Pro Paket',
                'verbose_name_plural': 'Sahip Pro Paketleri',
                'ordering': ['siralama', 'fiyat'],
            },
        ),
        migrations.CreateModel(
            name='SahipProAbonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.sahip', verbose_name='Sahip')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.sahippropaket', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Sahip Pro Abonelik',
                'verbose_name_plural': 'Sahip Pro Abonelikleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
