# Generated by Django 5.2.4 on 2025-09-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0002_sahippropaket_sahipproabonelik'),
        ('veteriner', '0011_remove_veterinermesaj_kullanici_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiket',
            name='musteri_adi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Müşteri Adı'),
        ),
        migrations.AddField(
            model_name='etiket',
            name='musteri_telefon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Müşteri Telefon'),
        ),
        migrations.AddField(
            model_name='etiket',
            name='satis_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Satış Tarihi'),
        ),
        migrations.AddField(
            model_name='etiket',
            name='satis_veteriner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_kunyalar', to='veteriner.veteriner', verbose_name='Künyeyi Satan Veteriner'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='danisman_atanma_sebebi',
            field=models.CharField(blank=True, choices=[('KUNYE_ALIMI', 'Künye Alımı'), ('ILCE_ESLESME', 'İlçe Eşleşmesi')], max_length=20, verbose_name='Danışman Atanma Sebebi'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='danisman_atanma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Danışman Atanma Tarihi'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='danisman_veteriner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danisman_oldugu_sahipler', to='veteriner.veteriner', verbose_name='Danışman Veteriner'),
        ),
    ]
