# Generated by Django 5.2.4 on 2025-09-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0003_etiket_musteri_adi_etiket_musteri_telefon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahip',
            name='danisman_atanma_sebebi',
            field=models.CharField(blank=True, choices=[('KUNYE_ALIMI', 'Künye Alımı'), ('ILCE_ESLESME', 'İlçe Eşleşmesi'), ('IL_ESLESME', 'İl Eşleşmesi')], max_length=20, verbose_name='Danışman Atanma Sebebi'),
        ),
    ]
