# Generated by Django 5.2.4 on 2025-10-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0004_alter_sahip_danisman_atanma_sebebi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etiket',
        ),
    ]
