# Generated by Django 5.2.4 on 2025-10-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0005_delete_etiket'),
        ('etiket', '0007_remove_etikettarama_etiket_etik_tarama__ac7b3e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('url', models.URLField(blank=True, help_text='Bildirimin yönlendireceği URL (örn: tarama detay sayfası)', null=True)),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('tur', models.CharField(choices=[('QR_TARAMA', 'QR Kod Tarama'), ('BULAN_BILGI', 'Bulan Kişi Bilgisi'), ('GENEL', 'Genel Bildirim')], default='GENEL', max_length=20, verbose_name='Bildirim Türü')),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='anahtarlik.sahip')),
                ('tarama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirimler', to='etiket.etikettarama')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-olusturma_zamani'],
            },
        ),
    ]
