# Generated by Django 5.2.4 on 2025-10-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0006_bildirim'),
        ('etiket', '0007_remove_etikettarama_etiket_etik_tarama__ac7b3e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildirim',
            name='sahip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='anahtarlik.sahip', verbose_name='Sahip'),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='tarama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirimler', to='etiket.etikettarama', verbose_name='İlgili Tarama'),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='url',
            field=models.URLField(blank=True, help_text='Bildirimin yönlendireceği URL (örn: tarama detay sayfası)', null=True, verbose_name='URL'),
        ),
    ]
