# Generated by Django 5.2.4 on 2025-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0007_alter_bildirim_sahip_alter_bildirim_tarama_and_more'),
        ('etiket', '0007_remove_etikettarama_etiket_etik_tarama__ac7b3e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='oncelik',
            field=models.CharField(choices=[('YUKSEK', 'Yüksek'), ('NORMAL', 'Normal'), ('DUSUK', 'Düşük')], default='NORMAL', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='tur',
            field=models.CharField(choices=[('QR_TARAMA', 'QR Kod Tarama'), ('BULAN_BILGI', 'Bulan Kişi Bilgisi'), ('KAYIP_HAYVAN', 'Kayıp Hayvan'), ('GENEL', 'Genel Bildirim'), ('SISTEM', 'Sistem Bildirimi'), ('PROMOSYON', 'Promosyon')], default='GENEL', max_length=20, verbose_name='Bildirim Türü'),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['sahip', '-olusturma_zamani'], name='anahtarlik__sahip_i_89bb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['tur', 'okundu'], name='anahtarlik__tur_a75a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['olusturma_zamani'], name='anahtarlik__olustur_1d25a5_idx'),
        ),
    ]
