# Generated by Django 5.2.4 on 2025-10-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0008_bildirim_oncelik_alter_bildirim_tur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciAdresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Örn: Ev, İş, Yazlık', max_length=100, verbose_name='Adres Başlığı')),
                ('adres_metni', models.TextField(verbose_name='Adres')),
                ('posta_kodu', models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu')),
                ('telefon', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan Adres')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.il', verbose_name='İl')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.ilce', verbose_name='İlçe')),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresler', to='anahtarlik.sahip')),
            ],
            options={
                'verbose_name': 'Kullanıcı Adresi',
                'verbose_name_plural': 'Kullanıcı Adresleri',
                'ordering': ['-varsayilan', '-olusturma_tarihi'],
            },
        ),
    ]
