# Generated by Django 5.2.4 on 2025-10-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0009_kullaniciadresi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilce',
            options={'ordering': ['il__ad', 'ad'], 'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahalleler', to='anahtarlik.ilce')),
            ],
            options={
                'verbose_name': 'Mahalle',
                'verbose_name_plural': 'Mahalleler',
                'ordering': ['ilce__il__ad', 'ilce__ad', 'ad'],
                'unique_together': {('ilce', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='kullaniciadresi',
            name='mahalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.mahalle', verbose_name='Mahalle'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='mahalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sahipleri', to='anahtarlik.mahalle'),
        ),
    ]
