# Generated by Django 5.2.4 on 2025-10-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0010_alter_ilce_options_mahalle_kullaniciadresi_mahalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullaniciadresi',
            name='mahalle_diger',
            field=models.CharField(blank=True, help_text='Mahalle listede yoksa buraya yazınız', max_length=200, verbose_name='Mahalle (Manuel)'),
        ),
        migrations.AddField(
            model_name='sahip',
            name='mahalle_diger',
            field=models.CharField(blank=True, help_text='Mahalle listede yoksa buraya yazınız', max_length=200, verbose_name='Mahalle (Manuel)'),
        ),
    ]
