# Generated by Django 5.2.4 on 2025-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0011_kullaniciadresi_mahalle_diger_sahip_mahalle_diger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSayfaAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmetler_baslik', models.CharField(default='Hizmetlerimiz', max_length=200, verbose_name='Hizmetler Başlık')),
                ('hizmetler_aciklama', models.TextField(default='Evcil dostlarınız için en iyi dijital kimlik ve sağlık takip çözümleri', verbose_name='Hizmetler Açıklama')),
                ('slide_gecis_suresi', models.IntegerField(default=5000, help_text="Hero slide'ların otomatik geçiş süresi (milisaniye)", verbose_name='Slide Geçiş Süresi (ms)')),
                ('slide_animasyon', models.CharField(choices=[('fade', 'Soluklaşma'), ('slide', 'Kaydırma'), ('zoom', 'Yakınlaşma')], default='fade', max_length=50, verbose_name='Slide Animasyon Tipi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Ayarı',
                'verbose_name_plural': 'Ana Sayfa Ayarları',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Ana başlık metni', max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(help_text='Açıklama metni', verbose_name='Açıklama')),
                ('arka_plan_resim', models.ImageField(blank=True, help_text='1920x1080 önerilen', null=True, upload_to='hero_slides/', verbose_name='Arka Plan Resmi')),
                ('arka_plan_renk', models.CharField(default='linear-gradient(135deg, rgba(255, 107, 157, 0.95) 0%, rgba(78, 205, 196, 0.85) 100%)', help_text='CSS gradient veya renk kodu', max_length=50, verbose_name='Arka Plan Renk/Gradient')),
                ('buton_1_metin', models.CharField(blank=True, max_length=100, verbose_name='Buton 1 Metin')),
                ('buton_1_url', models.CharField(blank=True, max_length=200, verbose_name='Buton 1 URL')),
                ('buton_2_metin', models.CharField(blank=True, max_length=100, verbose_name='Buton 2 Metin')),
                ('buton_2_url', models.CharField(blank=True, max_length=200, verbose_name='Buton 2 URL')),
                ('sira', models.IntegerField(default=0, help_text='Gösterim sırası (küçükten büyüğe)', verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': "Hero Slide'lar",
                'ordering': ['sira', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='HizmetKarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('aciklama', models.TextField(help_text='Kısa açıklama metni', verbose_name='Açıklama')),
                ('ikon', models.CharField(choices=[('fas fa-qrcode', 'QR Kod'), ('fas fa-calendar-check', 'Takvim/Randevu'), ('fas fa-shopping-cart', 'Alışveriş'), ('fas fa-paw', 'Pati'), ('fas fa-heartbeat', 'Kalp/Sağlık'), ('fas fa-user-md', 'Doktor'), ('fas fa-hospital', 'Hastane'), ('fas fa-notes-medical', 'Medikal Notlar'), ('fas fa-ambulance', 'Ambulans'), ('fas fa-shield-alt', 'Kalkan/Koruma'), ('fas fa-home', 'Ev'), ('fas fa-phone', 'Telefon'), ('fas fa-envelope', 'E-posta'), ('fas fa-map-marker-alt', 'Konum')], default='fas fa-paw', help_text='Font Awesome ikon sınıfı', max_length=50, verbose_name='İkon')),
                ('buton_metin', models.CharField(default='Keşfet', max_length=50, verbose_name='Buton Metni')),
                ('buton_url', models.CharField(max_length=200, verbose_name='Buton URL')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('animasyon_gecikmesi', models.IntegerField(default=100, help_text='AOS animasyon gecikmesi', verbose_name='Animasyon Gecikmesi (ms)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Hizmet Kartı',
                'verbose_name_plural': 'Hizmet Kartları',
                'ordering': ['sira', '-olusturma_tarihi'],
            },
        ),
    ]
