# Generated by Django 5.2.4 on 2025-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0012_anasayfaayar_heroslide_hizmetkarti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='arka_plan_renk',
            field=models.TextField(blank=True, default='linear-gradient(135deg, rgba(255, 107, 157, 0.95) 0%, rgba(78, 205, 196, 0.85) 100%)', help_text='CSS gradient veya renk kodu (sınırsız karakter)', null=True, verbose_name='Arka Plan Renk/Gradient'),
        ),
    ]
