# Generated by Django 5.2.4 on 2025-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0013_alter_heroslide_arka_plan_renk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='arka_plan_renk',
            field=models.TextField(default='linear-gradient(135deg, rgba(255, 107, 157, 0.95) 0%, rgba(78, 205, 196, 0.85) 100%)', help_text='CSS gradient veya renk kodu', verbose_name='Arka Plan Renk/Gradient'),
        ),
    ]
