# Generated by Django 5.2.4 on 2025-10-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0014_alter_heroslide_arka_plan_renk'),
        ('etiket', '0008_alter_etiket_qr_kod_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bildirim',
            name='anahtarlik__tur_a75a9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='bildirim',
            name='anahtarlik__olustur_1d25a5_idx',
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['okundu'], name='anahtarlik__okundu_adeaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['tur'], name='anahtarlik__tur_75ab61_idx'),
        ),
    ]
