# Generated by Django 5.2.4 on 2025-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0015_remove_bildirim_anahtarlik__tur_a75a9b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetkarti',
            name='detay_aciklama',
            field=models.TextField(blank=True, help_text='Hizmetin detaylı açıklaması', verbose_name='Detay Açıklama'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='detay_baslik',
            field=models.CharField(blank=True, help_text='Boş bırakılırsa ana başlık kullanılır', max_length=200, verbose_name='Detay Sayfası Başlık'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='detay_goruntu',
            field=models.ImageField(blank=True, help_text='Detay sayfasında gösterilecek görsel', null=True, upload_to='hizmet_detay/', verbose_name='Detay Görüntü'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='nasil_calisir',
            field=models.TextField(blank=True, help_text='Hizmetin nasıl çalıştığını açıklayan metin', verbose_name='Nasıl Çalışır?'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='ozellikler',
            field=models.TextField(blank=True, help_text='Her satıra bir özellik yazın (bullet points için)', verbose_name='Özellikler'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='satin_alma_buton_metni',
            field=models.CharField(default='Satın Al', max_length=50, verbose_name='Satın Alma Buton Metni'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='satin_alma_url',
            field=models.CharField(blank=True, help_text='Satın alma butonunun yönlendireceği URL', max_length=200, verbose_name='Satın Alma URL'),
        ),
        migrations.AddField(
            model_name='hizmetkarti',
            name='video_url',
            field=models.URLField(blank=True, help_text='Youtube veya diğer platform video linki (opsiyonel)', verbose_name='Video URL'),
        ),
    ]
