# Generated by Django 5.2.4 on 2025-11-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0016_hizmetkarti_detay_aciklama_hizmetkarti_detay_baslik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='detay_aciklama',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='detay_baslik',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='detay_goruntu',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='nasil_calisir',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='ozellikler',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='satin_alma_buton_metni',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='satin_alma_url',
        ),
        migrations.RemoveField(
            model_name='hizmetkarti',
            name='video_url',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='arka_plan_resim_mobil',
            field=models.ImageField(blank=True, help_text='1080x1920 önerilen (dikey görsel)', null=True, upload_to='hero_slides/mobile/', verbose_name='Arka Plan Resmi (Mobil)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='arka_plan_resim',
            field=models.ImageField(blank=True, help_text='1920x1080 önerilen (yatay görsel)', null=True, upload_to='hero_slides/', verbose_name='Arka Plan Resmi (Masaüstü)'),
        ),
    ]
