# Generated by Django 5.2.4 on 2025-11-10 14:36

from django.db import migrations, models


def set_evcilhayvan_defaults(apps, schema_editor):
    EvcilHayvan = apps.get_model('anahtarlik', 'EvcilHayvan')
    Tur = apps.get_model('anahtarlik', 'Tur')
    Irk = apps.get_model('anahtarlik', 'Irk')

    default_tur = Tur.objects.order_by('id').first()
    default_irk = Irk.objects.order_by('id').first()

    if default_tur:
        EvcilHayvan.objects.filter(tur__isnull=True).update(tur=default_tur)
    if default_irk:
        EvcilHayvan.objects.filter(irk__isnull=True).update(irk=default_irk)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0017_remove_hizmetkarti_detay_aciklama_and_more'),
    ]

    operations = [
        migrations.RunPython(set_evcilhayvan_defaults, noop),
        migrations.AlterField(
            model_name='evcilhayvan',
            name='tur',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='evcil_hayvanlar', to='anahtarlik.tur'),
        ),
        migrations.AlterField(
            model_name='evcilhayvan',
            name='irk',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='evcil_hayvanlar', to='anahtarlik.irk'),
        ),
    ]
