# Generated by Django 5.2.4 on 2025-11-22 10:25

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0018_enforce_evcilhayvan_fk'),
        ('veteriner', '0026_veteriner_ilk_giris_sifre_degistirildi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sahip',
            options={'ordering': ['-kullanici__date_joined'], 'verbose_name': 'Sahip', 'verbose_name_plural': 'Sahipler'},
        ),
        migrations.AlterField(
            model_name='sahip',
            name='acil_durum_kontagi',
            field=models.CharField(blank=True, help_text='Acil durum kontağı telefon numarası (05XX XXX XX XX formatında)', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon numarası geçerli formatta değil. (05XX XXX XX XX)', regex='^(\\+90|0)?[5][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='sahip',
            name='telefon',
            field=models.CharField(blank=True, help_text='Telefon numarası (05XX XXX XX XX formatında)', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon numarası geçerli formatta değil. (05XX XXX XX XX)', regex='^(\\+90|0)?[5][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='sahip',
            name='yedek_telefon',
            field=models.CharField(blank=True, help_text='Yedek telefon numarası (05XX XXX XX XX formatında)', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon numarası geçerli formatta değil. (05XX XXX XX XX)', regex='^(\\+90|0)?[5][0-9]{9}$')]),
        ),
        migrations.AddIndex(
            model_name='sahip',
            index=models.Index(fields=['il', 'ilce'], name='anahtarlik__il_id_a19000_idx'),
        ),
        migrations.AddIndex(
            model_name='sahip',
            index=models.Index(fields=['danisman_veteriner'], name='anahtarlik__danisma_40876a_idx'),
        ),
    ]
