# Generated by Django 5.2.4 on 2025-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_alter_petshop_il_alter_petshop_ilce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petshop',
            name='il',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='ilce',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='İlçe'),
        ),
    ]
