# Generated by Django 5.2.4 on 2025-10-05 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_auto_20251005_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='odeme_modeli',
            field=models.CharField(choices=[('PESIN', 'Peşin Ödeme'), ('KONSINYE', 'Konsinye (Numune) Ödeme')], default='PESIN', max_length=20, verbose_name='Ödeme Modeli'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='tercih_edilen_kargo',
            field=models.CharField(choices=[('ARAS', 'Aras Kargo'), ('YURTICI', 'Yurtiçi Kargo'), ('MNG', 'MNG Kargo'), ('DHL', 'DHL')], default='ARAS', max_length=20, verbose_name='Tercih Edilen Kargo'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='ticaret_sicil_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ticaret Sicil No'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='vergi_dairesi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='vergi_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vergi No'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='ad',
            field=models.CharField(max_length=150, verbose_name='Petshop Adı'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='adres_detay',
            field=models.TextField(blank=True, verbose_name='Adres Detayı'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='satis_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Satış Sayısı'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='tahsis_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Tahsis Sayısı'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='PetshopSiparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(max_length=50, unique=True, verbose_name='Sipariş No')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('kargo_ucreti', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo Ücreti')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('siparis_durumu', models.CharField(choices=[('BEKLENIYOR', 'Bekleniyor'), ('HAZIRLANIYOR', 'Hazırlanıyor'), ('KARGODA', 'Kargoda'), ('TESLIM', 'Teslim Edildi'), ('IPTAL', 'İptal Edildi')], default='BEKLENIYOR', max_length=20, verbose_name='Sipariş Durumu')),
                ('odeme_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ALINDI', 'Alındı'), ('IADE', 'İade Edildi'), ('MUAF', 'Muaf (Numune)')], default='BEKLEMEDE', max_length=20, verbose_name='Ödeme Durumu')),
                ('odeme_yontemi', models.CharField(choices=[('NAKIT', 'Nakit'), ('EFT', 'EFT/Havale'), ('KREDI', 'Kredi Kartı'), ('POS', 'Pos/Link'), ('DIGER', 'Diğer')], default='NAKIT', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('kargo_sirketi', models.CharField(blank=True, choices=[('ARAS', 'Aras Kargo'), ('YURTICI', 'Yurtiçi Kargo'), ('MNG', 'MNG Kargo'), ('DHL', 'DHL')], max_length=20, verbose_name='Kargo Şirketi')),
                ('kargo_takip_no', models.CharField(blank=True, max_length=100, verbose_name='Kargo Takip No')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('teslim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='petshop.petshop', verbose_name='Petshop')),
            ],
            options={
                'verbose_name': 'Petshop Siparişi',
                'verbose_name_plural': 'Petshop Siparişleri',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='PetshopSiparisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='petshop.petshopsiparis', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Sipariş Detayı',
                'verbose_name_plural': 'Sipariş Detayları',
            },
        ),
    ]
