# Generated by Django 5.2.4 on 2025-10-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0005_delete_etiket'),
        ('petshop', '0004_petshop_odeme_modeli_petshop_tercih_edilen_kargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petshop',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshoplar', to='anahtarlik.il', verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshoplar', to='anahtarlik.ilce', verbose_name='İlçe'),
        ),
    ]
