# Generated by Django 5.2.4 on 2025-10-20 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0009_kullaniciadresi'),
        ('petshop', '0005_alter_petshop_il_alter_petshop_ilce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petshopsiparisdetay',
            name='siparis',
        ),
        migrations.AlterModelOptions(
            name='petshop',
            options={},
        ),
        migrations.RemoveField(
            model_name='petshop',
            name='tercih_edilen_kargo',
        ),
        migrations.RemoveField(
            model_name='petshop',
            name='ticaret_sicil_no',
        ),
        migrations.RemoveField(
            model_name='petshop',
            name='vergi_dairesi',
        ),
        migrations.RemoveField(
            model_name='petshop',
            name='vergi_no',
        ),
        migrations.AddField(
            model_name='petshop',
            name='birincil_renk',
            field=models.CharField(blank=True, help_text='#667eea formatında HEX renk', max_length=7),
        ),
        migrations.AddField(
            model_name='petshop',
            name='calisan_sayisi',
            field=models.PositiveIntegerField(blank=True, help_text='Çalışan sayısı (opsiyonel)', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='carsamba_baslangic',
            field=models.TimeField(blank=True, help_text='Çarşamba başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='carsamba_bitis',
            field=models.TimeField(blank=True, help_text='Çarşamba bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='carsamba_kapali',
            field=models.BooleanField(default=False, help_text='Çarşamba kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cta_link',
            field=models.URLField(blank=True, help_text='Çağrı butonu linki (örn: WhatsApp linki veya Google Maps)'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cta_metin',
            field=models.CharField(blank=True, help_text='Çağrı butonu metni (örn: Mağazayı Ziyaret Et)', max_length=50),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cuma_baslangic',
            field=models.TimeField(blank=True, help_text='Cuma başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cuma_bitis',
            field=models.TimeField(blank=True, help_text='Cuma bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cuma_kapali',
            field=models.BooleanField(default=False, help_text='Cuma kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cumartesi_baslangic',
            field=models.TimeField(blank=True, help_text='Cumartesi başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cumartesi_bitis',
            field=models.TimeField(blank=True, help_text='Cumartesi bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='cumartesi_kapali',
            field=models.BooleanField(default=False, help_text='Cumartesi kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='degerlendirme_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petshop',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='goster_calisma_saatleri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='goster_galeri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='goster_hizmetler',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='goster_sosyal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet1_aciklama',
            field=models.TextField(blank=True, default='Kayıp evcil hayvanınızı bulmak için teknolojik çözüm.', help_text='1. Hizmet açıklaması'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet1_baslik',
            field=models.CharField(blank=True, default='QR Künyeler', help_text='1. Hizmet başlığı', max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet1_icon',
            field=models.CharField(blank=True, default='fa-qrcode', help_text='1. Hizmet ikonu (Font Awesome)', max_length=50),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet2_aciklama',
            field=models.TextField(blank=True, default='Profesyonel tüy bakımı ve tımar hizmetleri.', help_text='2. Hizmet açıklaması'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet2_baslik',
            field=models.CharField(blank=True, default='Pet Kuaför', help_text='2. Hizmet başlığı', max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet2_icon',
            field=models.CharField(blank=True, default='fa-cut', help_text='2. Hizmet ikonu (Font Awesome)', max_length=50),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet3_aciklama',
            field=models.TextField(blank=True, default='Sevimli dostlarınız için güvenli konaklama.', help_text='3. Hizmet açıklaması'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet3_baslik',
            field=models.CharField(blank=True, default='Pet Otel', help_text='3. Hizmet başlığı', max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='hizmet3_icon',
            field=models.CharField(blank=True, default='fa-hotel', help_text='3. Hizmet ikonu (Font Awesome)', max_length=50),
        ),
        migrations.AddField(
            model_name='petshop',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='kurulus_yili',
            field=models.PositiveIntegerField(blank=True, help_text='Kuruluş yılı (opsiyonel)', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo', null=True, upload_to='petshop_web/'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='magaza_buyuklugu',
            field=models.CharField(blank=True, choices=[('KUCUK', 'Küçük İşletme (0-50m²)'), ('ORTA', 'Orta Boy (50-150m²)'), ('BUYUK', 'Büyük Mağaza (150m²+)')], help_text='Mağaza büyüklüğü', max_length=10),
        ),
        migrations.AddField(
            model_name='petshop',
            name='magaza_tipi',
            field=models.CharField(blank=True, choices=[('FIZIKSEL', 'Sadece Fiziksel Mağaza'), ('ONLINE', 'Sadece Online'), ('HER_IKISI', 'Hem Fiziksel Hem Online')], help_text='Mağaza tipi', max_length=10),
        ),
        migrations.AddField(
            model_name='petshop',
            name='ortalama_puan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pazar_baslangic',
            field=models.TimeField(blank=True, help_text='Pazar başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pazar_bitis',
            field=models.TimeField(blank=True, help_text='Pazar bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pazar_kapali',
            field=models.BooleanField(default=True, help_text='Pazar kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pazartesi_baslangic',
            field=models.TimeField(blank=True, help_text='Pazartesi başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pazartesi_bitis',
            field=models.TimeField(blank=True, help_text='Pazartesi bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pazartesi_kapali',
            field=models.BooleanField(default=False, help_text='Pazartesi kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='persembe_baslangic',
            field=models.TimeField(blank=True, help_text='Perşembe başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='persembe_bitis',
            field=models.TimeField(blank=True, help_text='Perşembe bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='persembe_kapali',
            field=models.BooleanField(default=False, help_text='Perşembe kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pet_bakim',
            field=models.BooleanField(default=False, help_text='Pet bakım hizmeti veriyor mu?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pet_egitim',
            field=models.BooleanField(default=False, help_text='Eğitim hizmeti veriyor mu?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pet_hotel',
            field=models.BooleanField(default=False, help_text='Pet otel hizmeti veriyor mu?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pet_kuafor',
            field=models.BooleanField(default=False, help_text='Pet kuaför hizmeti veriyor mu?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='pet_taksi',
            field=models.BooleanField(default=False, help_text='Pet taksi hizmeti veriyor mu?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='sali_baslangic',
            field=models.TimeField(blank=True, help_text='Salı başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='sali_bitis',
            field=models.TimeField(blank=True, help_text='Salı bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='sali_kapali',
            field=models.BooleanField(default=False, help_text='Salı kapalı mı?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='tema',
            field=models.CharField(blank=True, help_text='Tema adı (örn: default, pastel)', max_length=20),
        ),
        migrations.AddField(
            model_name='petshop',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_aciklama',
            field=models.TextField(blank=True, help_text='Hakkımızda metni'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_aktif',
            field=models.BooleanField(default=False, help_text='Web sayfası aktif mi?'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_baslik',
            field=models.CharField(blank=True, help_text='Ana başlık (örn: Pati PetShop)', max_length=200),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_resim1',
            field=models.ImageField(blank=True, help_text='Ana görsel (Hakkımızda bölümü)', null=True, upload_to='petshop_web/'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_resim2',
            field=models.ImageField(blank=True, help_text='Galeri görseli 1', null=True, upload_to='petshop_web/'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_resim3',
            field=models.ImageField(blank=True, help_text='Galeri görseli 2', null=True, upload_to='petshop_web/'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_seo_aciklama',
            field=models.CharField(blank=True, help_text='SEO açıklama (max 160 karakter)', max_length=160),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_seo_anahtar_kelimeler',
            field=models.CharField(blank=True, help_text='SEO anahtar kelimeler (virgülle ayırın)', max_length=255),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_seo_baslik',
            field=models.CharField(blank=True, help_text='SEO başlık (max 70 karakter)', max_length=70),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_slogan',
            field=models.CharField(blank=True, help_text='Alt başlık/slogan (örn: Sevimli Dostlarınız İçin Her Şey)', max_length=300),
        ),
        migrations.AddField(
            model_name='petshop',
            name='web_slug',
            field=models.SlugField(blank=True, help_text='URL slug (otomatik oluşturulur)', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='petshop',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp numarası (örn: 905551112233)', max_length=20),
        ),
        migrations.AddField(
            model_name='petshop',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='ad',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='adres_detay',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshoplar', to='anahtarlik.il'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshoplar', to='anahtarlik.ilce'),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='odeme_modeli',
            field=models.CharField(choices=[('PESIN', 'Peşin Ödeme'), ('KONSINYE', 'Konsinye (Numune) Ödeme')], default='PESIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='satis_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='tahsis_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PetShopDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveIntegerField(help_text='1-5 arası puan', validators=[django.core.validators.MinValueValidator(1)])),
                ('yorum', models.TextField(blank=True)),
                ('musteri_adi', models.CharField(max_length=100)),
                ('musteri_telefon', models.CharField(blank=True, max_length=15)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='petshop.petshop')),
            ],
            options={
                'verbose_name': 'PetShop Değerlendirmesi',
                'verbose_name_plural': 'PetShop Değerlendirmeleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiparisIstemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_edilen_adet', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)])),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kargolandimi', models.BooleanField(default=False)),
                ('kargo_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kargo_sirketi', models.CharField(blank=True, choices=[('ARAS', 'Aras Kargo'), ('YURTICI', 'Yurtiçi Kargo'), ('MNG', 'MNG Kargo'), ('DHL', 'DHL')], max_length=20)),
                ('kargo_takip_no', models.CharField(blank=True, max_length=100)),
                ('farkli_adres_kullan', models.BooleanField(default=False)),
                ('adres_detay', models.TextField(blank=True)),
                ('numune_mi', models.BooleanField(default=False)),
                ('odeme_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ALINDI', 'Alındı'), ('IADE', 'İade Edildi'), ('MUAF', 'Muaf (Numune)')], default='BEKLEMEDE', max_length=12)),
                ('odeme_tutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odeme_para_birimi', models.CharField(default='TRY', max_length=6)),
                ('odeme_yontemi', models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('EFT', 'EFT/Havale'), ('KREDI', 'Kredi Kartı'), ('POS', 'Pos/Link'), ('DIGER', 'Diğer')], max_length=10)),
                ('odeme_alinma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('il', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshop_siparis_istekleri', to='anahtarlik.il')),
                ('ilce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshop_siparis_istekleri', to='anahtarlik.ilce')),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_istekleri', to='petshop.petshop')),
            ],
        ),
        migrations.DeleteModel(
            name='PetshopSiparis',
        ),
        migrations.DeleteModel(
            name='PetshopSiparisDetay',
        ),
    ]
