# Generated by Django 5.2.4 on 2025-10-20 15:34

from django.db import migrations
from django.utils.text import slugify


def update_slugs_to_ascii(apps, schema_editor):
    """Mevcut Türkçe karakterli slug'ları İngilizce karşılıklarına çevir"""
    PetShop = apps.get_model('petshop', 'PetShop')
    
    # Türkçe karakter dönüşüm tablosu
    tr_map = str.maketrans('çğıöşüÇĞIÖŞÜ', 'cgiosuCGIOSU')
    
    for petshop in PetShop.objects.all():
        if petshop.web_slug:
            # Mevcut slug'u temizle
            temiz_slug = petshop.web_slug.translate(tr_map)
            base_slug = slugify(temiz_slug, allow_unicode=False)
            
            # Benzersizlik kontrolü
            slug = base_slug
            counter = 1
            while PetShop.objects.filter(web_slug=slug).exclude(pk=petshop.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            petshop.web_slug = slug
            petshop.save(update_fields=['web_slug'])


def reverse_update_slugs(apps, schema_editor):
    """Geri alma işlemi - slug'ları orijinal isimlere göre yeniden oluştur"""
    PetShop = apps.get_model('petshop', 'PetShop')
    
    for petshop in PetShop.objects.all():
        if petshop.ad:
            base_slug = slugify(petshop.ad, allow_unicode=True)
            slug = base_slug
            counter = 1
            while PetShop.objects.filter(web_slug=slug).exclude(pk=petshop.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            petshop.web_slug = slug
            petshop.save(update_fields=['web_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0006_remove_petshopsiparisdetay_siparis_and_more'),
    ]

    operations = [
        migrations.RunPython(update_slugs_to_ascii, reverse_update_slugs),
    ]
