# Generated by Django 5.2.4 on 2025-10-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0007_update_slugs_to_ascii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petshop',
            name='degerlendirme_sayisi',
        ),
        migrations.RemoveField(
            model_name='petshop',
            name='ortalama_puan',
        ),
        migrations.DeleteModel(
            name='PetShopDegerlendirme',
        ),
    ]
