# Generated by Django 5.2.4 on 2025-10-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0011_kullaniciadresi_mahalle_diger_sahip_mahalle_diger'),
        ('petshop', '0008_remove_petshop_degerlendirme_sayisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='mahalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshoplar', to='anahtarlik.mahalle'),
        ),
        migrations.AddField(
            model_name='petshop',
            name='mahalle_diger',
            field=models.CharField(blank=True, help_text='Mahalle listede yoksa buraya yazınız', max_length=200, verbose_name='Mahalle (Manuel)'),
        ),
    ]
