# Generated by Django 4.2 on 2025-10-04 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anahtarlik', '0005_delete_etiket'),
        ('petshop', '0002_alter_petshop_il_alter_petshop_ilce'),
        ('veteriner', '0014_remove_veteriner_deneyim_yili'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seri_numarasi', models.CharField(max_length=50, unique=True)),
                ('qr_kod_url', models.URLField(blank=True)),
                ('aktif', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kilitli', models.BooleanField(default=False)),
                ('kanal', models.CharField(choices=[('ONLINE', 'Online'), ('VET', 'Veteriner'), ('SHOP', 'Petshop')], max_length=10)),
                ('tahsis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('first_activated_at', models.DateTimeField(blank=True, null=True)),
                ('aktiflestirme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('aktivasyon_sayisi', models.PositiveIntegerField(default=0)),
                ('satis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Satış Tarihi')),
                ('musteri_adi', models.CharField(blank=True, max_length=100, verbose_name='Müşteri Adı')),
                ('musteri_telefon', models.CharField(blank=True, max_length=15, verbose_name='Müşteri Telefon')),
                ('aktiflestiren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiflestirdigi_etiketler', to=settings.AUTH_USER_MODEL)),
                ('evcil_hayvan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anahtarlik.evcilhayvan')),
                ('satici_petshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_etiketler', to='petshop.petshop')),
                ('satici_veteriner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_etiketler', to='veteriner.veteriner')),
                ('satis_veteriner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sattigi_kunyalar', to='veteriner.veteriner', verbose_name='Künyeyi Satan Veteriner')),
            ],
            options={
                'constraints': [models.CheckConstraint(check=models.Q(('kanal__isnull', True), models.Q(('kanal', 'VET'), _negated=True), ('satici_veteriner__isnull', False), _connector='OR'), name='etiket_vet_icin_veteriner_zorunlu'), models.CheckConstraint(check=models.Q(('kanal__isnull', True), models.Q(('kanal', 'SHOP'), _negated=True), ('satici_petshop__isnull', False), _connector='OR'), name='etiket_shop_icin_petshop_zorunlu'), models.CheckConstraint(check=models.Q(('kanal__isnull', True), models.Q(('kanal', 'ONLINE'), _negated=True), models.Q(('satici_veteriner__isnull', True), ('satici_petshop__isnull', True)), _connector='OR'), name='etiket_online_icin_partner_bos')],
            },
        ),
    ]
