# Generated by Django 5.2.4 on 2025-10-04 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0005_delete_etiket'),
        ('etiket', '0001_initial'),
        ('petshop', '0002_alter_petshop_il_alter_petshop_ilce'),
        ('veteriner', '0014_remove_veteriner_deneyim_yili'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etiket',
            name='adres_bayi',
            field=models.TextField(blank=True, verbose_name='Adres Bayi'),
        ),
        migrations.AddField(
            model_name='etiket',
            name='adres_kullanici',
            field=models.TextField(blank=True, verbose_name='Adres Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='etiket',
            name='kanal',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('VET', 'Veteriner'), ('SHOP', 'Petshop'), ('TAHSISSIZ', 'Tahsissiz')], max_length=10),
        ),
        migrations.AlterField(
            model_name='etiket',
            name='seri_numarasi',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='etiket',
            constraint=models.CheckConstraint(condition=models.Q(('kanal__isnull', True), models.Q(('kanal', 'TAHSISSIZ'), _negated=True), models.Q(('satici_veteriner__isnull', True), ('satici_petshop__isnull', True)), _connector='OR'), name='etiket_tahsissiz_icin_partner_bos'),
        ),
    ]
