# Generated by Django 5.2.4 on 2025-10-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0002_etiket_adres_bayi_etiket_adres_kullanici_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiket',
            name='son_kullanma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanma Tarihi'),
        ),
    ]
