# Generated by Django 5.2.4 on 2025-10-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0003_etiket_son_kullanma_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiketKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('renk', models.CharField(default='#007bff', help_text='Hex renk kodu (örn: #ff0000)', max_length=7, verbose_name='Renk Kodu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Etiket Kategorisi',
                'verbose_name_plural': 'Etiket Kategorileri',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='etiket',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiketler', to='etiket.etiketkategori', verbose_name='Etiket Kategorisi'),
        ),
    ]
