# Generated by Django 5.2.4 on 2025-10-05 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0004_etiketkategori_etiket_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiketKategoriFotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='etiket_kategori_fotograflari/', verbose_name='Fotoğraf')),
                ('baslik', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, help_text='Görüntüleme sırası (0 = en üstte)', verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='etiket.etiketkategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Etiket Kategori Fotoğrafı',
                'verbose_name_plural': 'Etiket Kategori Fotoğrafları',
                'ordering': ['sira', '-olusturulma_tarihi'],
            },
        ),
    ]
