# Generated by Django 5.2.4 on 2025-10-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0005_etiketkategorifotografi'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiketTarama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarama_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Tarama Zamanı')),
                ('gps_latitude', models.FloatField(blank=True, null=True, verbose_name='GPS Enlem')),
                ('gps_longitude', models.FloatField(blank=True, null=True, verbose_name='GPS Boylam')),
                ('gps_dogruluk', models.FloatField(blank=True, help_text='Koordinatların doğruluk yarıçapı', null=True, verbose_name='GPS Doğruluk (metre)')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('ip_sehir', models.CharField(blank=True, max_length=100, verbose_name='IP Şehir')),
                ('ip_ulke', models.CharField(blank=True, max_length=100, verbose_name='IP Ülke')),
                ('ip_lokasyon_text', models.CharField(blank=True, max_length=255, verbose_name='IP Lokasyon Metni')),
                ('bulan_isim', models.CharField(blank=True, max_length=100, verbose_name='Bulan Kişi İsmi')),
                ('bulan_telefon', models.CharField(blank=True, max_length=20, verbose_name='Bulan Kişi Telefonu')),
                ('bulan_email', models.EmailField(blank=True, max_length=254, verbose_name='Bulan Kişi E-postası')),
                ('bulan_mesaj', models.TextField(blank=True, verbose_name='Bulan Kişi Mesajı')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referrer')),
                ('tarayici_dili', models.CharField(blank=True, max_length=10, verbose_name='Tarayıcı Dili')),
                ('email_gonderildi', models.BooleanField(default=False, verbose_name='E-posta Gönderildi')),
                ('email_gonderim_zamani', models.DateTimeField(blank=True, null=True, verbose_name='E-posta Gönderim Zamanı')),
                ('etiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taramalar', to='etiket.etiket', verbose_name='Etiket')),
            ],
            options={
                'verbose_name': 'Etiket Tarama',
                'verbose_name_plural': 'Etiket Taramaları',
                'ordering': ['-tarama_zamani'],
                'indexes': [models.Index(fields=['etiket', '-tarama_zamani'], name='etiket_etik_etiket__611cd1_idx'), models.Index(fields=['tarama_zamani'], name='etiket_etik_tarama__ac7b3e_idx')],
            },
        ),
    ]
