# Generated by Django 5.2.4 on 2025-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0006_etikettarama'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='etikettarama',
            name='etiket_etik_tarama__ac7b3e_idx',
        ),
        migrations.AddIndex(
            model_name='etikettarama',
            index=models.Index(fields=['-tarama_zamani'], name='etiket_etik_tarama__738280_idx'),
        ),
        migrations.AddIndex(
            model_name='etikettarama',
            index=models.Index(fields=['email_gonderildi'], name='etiket_etik_email_g_2a5871_idx'),
        ),
        migrations.AddIndex(
            model_name='etikettarama',
            index=models.Index(fields=['gps_latitude', 'gps_longitude'], name='etiket_etik_gps_lat_0c329c_idx'),
        ),
    ]
