# Generated by Django 5.2.4 on 2025-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0007_remove_etikettarama_etiket_etik_tarama__ac7b3e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiket',
            name='qr_kod_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
