# Generated by Django 5.2.4 on 2025-10-27 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0008_alter_etiket_qr_kod_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiketYenileme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yenileme_ucreti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yenileme Ücreti')),
                ('odeme_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ODENDI', 'Ödendi'), ('IPTAL', 'İptal'), ('IADE', 'İade')], default='BEKLEMEDE', max_length=20, verbose_name='Ödeme Durumu')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Payment Intent ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Session ID')),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('odeme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('yeni_bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Yeni Bitiş Tarihi')),
                ('yenileme_suresi_gun', models.IntegerField(default=365, verbose_name='Yenileme Süresi (Gün)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('etiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yenilemeler', to='etiket.etiket')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiket_yenilemeleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etiket Yenileme',
                'verbose_name_plural': 'Etiket Yenilemeleri',
                'ordering': ['-talep_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='EtiketYenilemeFiyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yenileme Fiyatı (TL)')),
                ('sure_gun', models.IntegerField(default=365, verbose_name='Süre (Gün)')),
                ('veteriner_indirim_yuzde', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Veteriner İndirimi (%)')),
                ('petshop_indirim_yuzde', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='PetShop İndirimi (%)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('etiket_kategori', models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel fiyat olur', null=True, on_delete=django.db.models.deletion.CASCADE, to='etiket.etiketkategori', verbose_name='Etiket Kategorisi')),
            ],
            options={
                'verbose_name': 'Etiket Yenileme Fiyatı',
                'verbose_name_plural': 'Etiket Yenileme Fiyatları',
                'ordering': ['sira', 'fiyat'],
                'unique_together': {('etiket_kategori', 'sure_gun')},
            },
        ),
    ]
