# Generated by Django 5.2.4 on 2025-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiket', '0009_etiketyenileme_etiketyenilemefiyati'),
    ]

    operations = [
        migrations.AddField(
            model_name='etikettarama',
            name='konum_kaynagi',
            field=models.CharField(choices=[('GPS', 'GPS (Gerçek Konum)'), ('IP', 'IP (Tahmini Konum)'), ('MANUEL', 'Manuel (Kullanıcı Girdi)')], default='IP', help_text='Konumun nasıl alındığı (GPS=Gerçek, IP=Tahmini, MANUEL=Kullanıcı girdi)', max_length=10, verbose_name='Konum Kaynağı'),
        ),
    ]
