# Generated by Django 5.2.4 on 2025-11-22 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0019_alter_sahip_options_alter_sahip_acil_durum_kontagi_and_more'),
        ('etiket', '0010_etikettarama_konum_kaynagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiket',
            name='evcil_hayvan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiket', to='anahtarlik.evcilhayvan'),
        ),
    ]
