# Generated by Django 4.2.26 on 2025-11-23 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anahtarlik", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Randevu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("musteri_adi", models.CharField(max_length=100)),
                ("musteri_telefon", models.CharField(max_length=15)),
                (
                    "musteri_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("hayvan_adi", models.CharField(max_length=100)),
                ("hayvan_turu", models.CharField(blank=True, max_length=50)),
                ("hayvan_yasi", models.CharField(blank=True, max_length=20)),
                ("hayvan_cinsiyet", models.CharField(blank=True, max_length=10)),
                ("sorun_aciklamasi", models.TextField(blank=True)),
                ("tarih", models.DateField()),
                ("saat", models.TimeField()),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("BEKLENIYOR", "Bekleniyor"),
                            ("ONAYLANDI", "Onaylandı"),
                            ("IPTAL", "İptal"),
                            ("TAMAMLANDI", "Tamamlandı"),
                        ],
                        default="BEKLENIYOR",
                        max_length=20,
                    ),
                ),
                ("notlar", models.TextField(blank=True, null=True)),
                (
                    "fiyat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "odeme_durumu",
                    models.CharField(
                        choices=[
                            ("BEKLEMEDE", "Beklemede"),
                            ("ALINDI", "Alındı"),
                            ("IADE", "İade Edildi"),
                            ("MUAF", "Muaf (Numune)"),
                        ],
                        default="BEKLEMEDE",
                        max_length=20,
                    ),
                ),
                (
                    "odeme_yontemi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NAKIT", "Nakit"),
                            ("EFT", "EFT/Havale"),
                            ("KREDI", "Kredi Kartı"),
                            ("POS", "Pos/Link"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Randevu",
                "verbose_name_plural": "Randevular",
                "ordering": ["-tarih", "-saat"],
            },
        ),
        migrations.CreateModel(
            name="Veteriner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=150)),
                ("telefon", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "mahalle_diger",
                    models.CharField(
                        blank=True,
                        help_text="Mahalle listede yoksa buraya yazınız",
                        max_length=200,
                        verbose_name="Mahalle (Manuel)",
                    ),
                ),
                ("adres_detay", models.TextField(blank=True)),
                ("aktif", models.BooleanField(default=True)),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                (
                    "odeme_modeli",
                    models.CharField(
                        choices=[
                            ("PESIN", "Peşin Ödeme"),
                            ("KONSINYE", "Konsinye (Numune) Ödeme"),
                        ],
                        default="PESIN",
                        max_length=10,
                    ),
                ),
                (
                    "ilk_giris_sifre_degistirildi",
                    models.BooleanField(
                        default=False,
                        help_text="Admin tarafından oluşturulan kullanıcının ilk girişte şifresini değiştirdiğini belirtir.",
                        verbose_name="İlk Giriş Şifre Değiştirildi",
                    ),
                ),
                ("tahsis_sayisi", models.PositiveIntegerField(default=0)),
                ("satis_sayisi", models.PositiveIntegerField(default=0)),
                (
                    "uzmanlik_alanlari",
                    models.TextField(
                        blank=True, help_text="Uzmanlık alanları (virgülle ayırın)"
                    ),
                ),
                (
                    "calisma_saatleri",
                    models.TextField(blank=True, help_text="Çalışma saatleri"),
                ),
                (
                    "acil_hizmet",
                    models.BooleanField(
                        default=False, help_text="Acil hizmet veriyor mu?"
                    ),
                ),
                (
                    "evde_hizmet",
                    models.BooleanField(
                        default=False, help_text="Evde hizmet veriyor mu?"
                    ),
                ),
                (
                    "hizmet_verilen_ilceler",
                    models.TextField(
                        blank=True, help_text="Hizmet verilen ilçeler (virgülle ayırın)"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("instagram", models.CharField(blank=True, max_length=100)),
                ("facebook", models.CharField(blank=True, max_length=100)),
                ("twitter", models.CharField(blank=True, max_length=100)),
                ("linkedin", models.CharField(blank=True, max_length=100)),
                ("youtube", models.CharField(blank=True, max_length=100)),
                (
                    "tema",
                    models.CharField(
                        blank=True,
                        help_text="Tema adı (örn: default, pastel)",
                        max_length=20,
                    ),
                ),
                (
                    "birincil_renk",
                    models.CharField(
                        blank=True,
                        help_text="#667eea formatında HEX renk",
                        max_length=7,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo",
                        null=True,
                        upload_to="veteriner_web/",
                    ),
                ),
                (
                    "cta_metin",
                    models.CharField(
                        blank=True,
                        help_text="Çağrı butonu metni (örn: Randevu Alın)",
                        max_length=50,
                    ),
                ),
                (
                    "cta_link",
                    models.URLField(
                        blank=True,
                        help_text="Çağrı butonu linki (örn: randevu ya da WhatsApp linki)",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp numarası (örn: 905551112233)",
                        max_length=20,
                    ),
                ),
                ("goster_sosyal", models.BooleanField(default=True)),
                ("goster_hizmetler", models.BooleanField(default=True)),
                ("goster_calisma_saatleri", models.BooleanField(default=True)),
                ("goster_galeri", models.BooleanField(default=True)),
                (
                    "pazartesi_baslangic",
                    models.TimeField(
                        blank=True, help_text="Pazartesi başlangıç saati", null=True
                    ),
                ),
                (
                    "pazartesi_bitis",
                    models.TimeField(
                        blank=True, help_text="Pazartesi bitiş saati", null=True
                    ),
                ),
                (
                    "pazartesi_kapali",
                    models.BooleanField(
                        default=False, help_text="Pazartesi kapalı mı?"
                    ),
                ),
                (
                    "sali_baslangic",
                    models.TimeField(
                        blank=True, help_text="Salı başlangıç saati", null=True
                    ),
                ),
                (
                    "sali_bitis",
                    models.TimeField(
                        blank=True, help_text="Salı bitiş saati", null=True
                    ),
                ),
                (
                    "sali_kapali",
                    models.BooleanField(default=False, help_text="Salı kapalı mı?"),
                ),
                (
                    "carsamba_baslangic",
                    models.TimeField(
                        blank=True, help_text="Çarşamba başlangıç saati", null=True
                    ),
                ),
                (
                    "carsamba_bitis",
                    models.TimeField(
                        blank=True, help_text="Çarşamba bitiş saati", null=True
                    ),
                ),
                (
                    "carsamba_kapali",
                    models.BooleanField(default=False, help_text="Çarşamba kapalı mı?"),
                ),
                (
                    "persembe_baslangic",
                    models.TimeField(
                        blank=True, help_text="Perşembe başlangıç saati", null=True
                    ),
                ),
                (
                    "persembe_bitis",
                    models.TimeField(
                        blank=True, help_text="Perşembe bitiş saati", null=True
                    ),
                ),
                (
                    "persembe_kapali",
                    models.BooleanField(default=False, help_text="Perşembe kapalı mı?"),
                ),
                (
                    "cuma_baslangic",
                    models.TimeField(
                        blank=True, help_text="Cuma başlangıç saati", null=True
                    ),
                ),
                (
                    "cuma_bitis",
                    models.TimeField(
                        blank=True, help_text="Cuma bitiş saati", null=True
                    ),
                ),
                (
                    "cuma_kapali",
                    models.BooleanField(default=False, help_text="Cuma kapalı mı?"),
                ),
                (
                    "cumartesi_baslangic",
                    models.TimeField(
                        blank=True, help_text="Cumartesi başlangıç saati", null=True
                    ),
                ),
                (
                    "cumartesi_bitis",
                    models.TimeField(
                        blank=True, help_text="Cumartesi bitiş saati", null=True
                    ),
                ),
                (
                    "cumartesi_kapali",
                    models.BooleanField(
                        default=False, help_text="Cumartesi kapalı mı?"
                    ),
                ),
                (
                    "pazar_baslangic",
                    models.TimeField(
                        blank=True, help_text="Pazar başlangıç saati", null=True
                    ),
                ),
                (
                    "pazar_bitis",
                    models.TimeField(
                        blank=True, help_text="Pazar bitiş saati", null=True
                    ),
                ),
                (
                    "pazar_kapali",
                    models.BooleanField(default=True, help_text="Pazar kapalı mı?"),
                ),
                (
                    "ortalama_puan",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("degerlendirme_sayisi", models.PositiveIntegerField(default=0)),
                (
                    "web_baslik",
                    models.CharField(
                        blank=True,
                        help_text="Ana başlık (örn: Pati Veteriner Kliniği)",
                        max_length=200,
                    ),
                ),
                (
                    "web_slogan",
                    models.CharField(
                        blank=True,
                        help_text="Alt başlık/slogan (örn: Sevimli Dostlarınız İçin En İyi Bakım)",
                        max_length=300,
                    ),
                ),
                (
                    "web_aciklama",
                    models.TextField(blank=True, help_text="Hakkımızda metni"),
                ),
                (
                    "hizmet1_baslik",
                    models.CharField(
                        blank=True,
                        default="Genel Muayene",
                        help_text="1. Hizmet başlığı",
                        max_length=100,
                    ),
                ),
                (
                    "hizmet1_aciklama",
                    models.TextField(
                        blank=True,
                        default="Detaylı fiziksel muayene, teşhis ve sağlık kontrolü.",
                        help_text="1. Hizmet açıklaması",
                    ),
                ),
                (
                    "hizmet1_icon",
                    models.CharField(
                        blank=True,
                        default="🩺",
                        help_text="1. Hizmet ikonu (emoji)",
                        max_length=20,
                    ),
                ),
                (
                    "hizmet2_baslik",
                    models.CharField(
                        blank=True,
                        default="Aşılama & Tedavi",
                        help_text="2. Hizmet başlığı",
                        max_length=100,
                    ),
                ),
                (
                    "hizmet2_aciklama",
                    models.TextField(
                        blank=True,
                        default="Koruyucu aşı programları ve hastalık tedavileri.",
                        help_text="2. Hizmet açıklaması",
                    ),
                ),
                (
                    "hizmet2_icon",
                    models.CharField(
                        blank=True,
                        default="💉",
                        help_text="2. Hizmet ikonu (emoji)",
                        max_length=20,
                    ),
                ),
                (
                    "hizmet3_baslik",
                    models.CharField(
                        blank=True,
                        default="Laboratuvar",
                        help_text="3. Hizmet başlığı",
                        max_length=100,
                    ),
                ),
                (
                    "hizmet3_aciklama",
                    models.TextField(
                        blank=True,
                        default="Kan tahlili, röntgen, ultrason gibi teşhis yöntemleri.",
                        help_text="3. Hizmet açıklaması",
                    ),
                ),
                (
                    "hizmet3_icon",
                    models.CharField(
                        blank=True,
                        default="🔬",
                        help_text="3. Hizmet ikonu (emoji)",
                        max_length=20,
                    ),
                ),
                (
                    "web_resim1",
                    models.ImageField(
                        blank=True,
                        help_text="Ana görsel (Hakkımızda bölümü)",
                        null=True,
                        upload_to="veteriner_web/",
                    ),
                ),
                (
                    "web_resim2",
                    models.ImageField(
                        blank=True,
                        help_text="Galeri görseli 1",
                        null=True,
                        upload_to="veteriner_web/",
                    ),
                ),
                (
                    "web_resim3",
                    models.ImageField(
                        blank=True,
                        help_text="Galeri görseli 2",
                        null=True,
                        upload_to="veteriner_web/",
                    ),
                ),
                (
                    "web_seo_baslik",
                    models.CharField(
                        blank=True,
                        help_text="SEO başlık (max 70 karakter)",
                        max_length=70,
                    ),
                ),
                (
                    "web_seo_aciklama",
                    models.CharField(
                        blank=True,
                        help_text="SEO açıklama (max 160 karakter)",
                        max_length=160,
                    ),
                ),
                (
                    "web_seo_anahtar_kelimeler",
                    models.CharField(
                        blank=True,
                        help_text="SEO anahtar kelimeler (virgülle ayırın)",
                        max_length=255,
                    ),
                ),
                (
                    "web_slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL slug (otomatik oluşturulur)",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "web_aktif",
                    models.BooleanField(
                        default=False, help_text="Web sayfası aktif mi?"
                    ),
                ),
                (
                    "konum_koordinat",
                    models.CharField(
                        blank=True,
                        help_text="Google Maps formatında: 38.231952, 42.428070",
                        max_length=40,
                        null=True,
                        verbose_name="Koordinat",
                    ),
                ),
                (
                    "il",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinerler",
                        to="anahtarlik.il",
                    ),
                ),
                (
                    "ilce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinerler",
                        to="anahtarlik.ilce",
                    ),
                ),
                (
                    "kullanici",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veteriner_profili",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mahalle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinerler",
                        to="anahtarlik.mahalle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VeterinerHizmet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hizmet_adi", models.CharField(max_length=200)),
                (
                    "hizmet_turu",
                    models.CharField(
                        choices=[
                            ("GENEL", "Genel Muayene"),
                            ("ACIL", "Acil Müdahale"),
                            ("OPERASYON", "Operasyon"),
                            ("KONTROL", "Kontrol Muayenesi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("aciklama", models.TextField(blank=True)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sure_dakika",
                    models.PositiveIntegerField(help_text="Tahmini süre (dakika)"),
                ),
                ("aktif", models.BooleanField(default=True)),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "veteriner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hizmetler",
                        to="veteriner.veteriner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veteriner Hizmeti",
                "verbose_name_plural": "Veteriner Hizmetleri",
                "ordering": ["hizmet_adi"],
            },
        ),
        migrations.CreateModel(
            name="VeterinerDegerlendirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puan",
                    models.PositiveIntegerField(
                        help_text="1-5 arası puan",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("yorum", models.TextField(blank=True)),
                ("musteri_adi", models.CharField(max_length=100)),
                ("musteri_telefon", models.CharField(blank=True, max_length=15)),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("aktif", models.BooleanField(default=True)),
                (
                    "randevu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degerlendirme",
                        to="veteriner.randevu",
                    ),
                ),
                (
                    "veteriner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degerlendirmeler",
                        to="veteriner.veteriner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veteriner Değerlendirmesi",
                "verbose_name_plural": "Veteriner Değerlendirmeleri",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="SiparisIstemi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "talep_edilen_adet",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(5)],
                    ),
                ),
                ("talep_tarihi", models.DateTimeField(auto_now_add=True)),
                ("onaylandi", models.BooleanField(default=False)),
                ("onay_tarihi", models.DateTimeField(blank=True, null=True)),
                ("kargolandimi", models.BooleanField(default=False)),
                ("kargo_tarihi", models.DateTimeField(blank=True, null=True)),
                (
                    "kargo_sirketi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARAS", "Aras Kargo"),
                            ("YURTICI", "Yurtiçi Kargo"),
                            ("MNG", "MNG Kargo"),
                            ("DHL", "DHL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kargo_takip_no", models.CharField(blank=True, max_length=100)),
                ("farkli_adres_kullan", models.BooleanField(default=False)),
                ("adres_detay", models.TextField(blank=True)),
                ("numune_mi", models.BooleanField(default=False)),
                (
                    "odeme_durumu",
                    models.CharField(
                        choices=[
                            ("BEKLEMEDE", "Beklemede"),
                            ("ALINDI", "Alındı"),
                            ("IADE", "İade Edildi"),
                            ("MUAF", "Muaf (Numune)"),
                        ],
                        default="BEKLEMEDE",
                        max_length=12,
                    ),
                ),
                (
                    "odeme_tutari",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("odeme_para_birimi", models.CharField(default="TRY", max_length=6)),
                (
                    "odeme_yontemi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NAKIT", "Nakit"),
                            ("EFT", "EFT/Havale"),
                            ("KREDI", "Kredi Kartı"),
                            ("POS", "Pos/Link"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("odeme_alinma_tarihi", models.DateTimeField(blank=True, null=True)),
                (
                    "il",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siparis_istekleri",
                        to="anahtarlik.il",
                    ),
                ),
                (
                    "ilce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siparis_istekleri",
                        to="anahtarlik.ilce",
                    ),
                ),
                (
                    "veteriner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siparis_istekleri",
                        to="veteriner.veteriner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="randevu",
            name="hizmet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="randevular",
                to="veteriner.veterinerhizmet",
            ),
        ),
        migrations.AddField(
            model_name="randevu",
            name="veteriner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="randevular",
                to="veteriner.veteriner",
            ),
        ),
        migrations.CreateModel(
            name="VeterinerYuzde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yuzde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Yüzde",
                    ),
                ),
                (
                    "son_guncelleme",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "ilce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veteriner_yuzdeleri",
                        to="anahtarlik.ilce",
                    ),
                ),
                (
                    "veteriner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yuzde_dagilimlari",
                        to="veteriner.veteriner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veteriner Yüzde Dağılımı",
                "verbose_name_plural": "Veteriner Yüzde Dağılımları",
                "ordering": ["-yuzde", "veteriner__ad"],
                "unique_together": {("veteriner", "ilce")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="randevu",
            unique_together={("veteriner", "tarih", "saat")},
        ),
    ]
