# Generated by Django 4.2.26 on 2025-12-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0001_initial'),
    ]

    operations = [
    ]
