# Generated by Django 4.2.26 on 2025-12-08 18:08

from django.db import migrations, models


def set_aktif_for_web_aktif_veteriners(apps, schema_editor):
    """Web sayfası aktif olan veterinerleri aktif yap"""
    Veteriner = apps.get_model('veteriner', 'Veteriner')
    Veteriner.objects.filter(web_aktif=True, web_slug__isnull=False).exclude(web_slug='').update(aktif=True)


def reverse_set_aktif(apps, schema_editor):
    """Geri alma - tüm veterinerleri aktif yap"""
    Veteriner = apps.get_model('veteriner', 'Veteriner')
    Veteriner.objects.all().update(aktif=True)


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0002_fix_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteriner',
            name='satis_sayisi',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='tahsis_sayisi',
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='aktif',
            field=models.BooleanField(default=False, help_text='Veteriner aktif mi? (Web sayfası yayına alınınca otomatik aktif olur)'),
        ),
        migrations.RunPython(set_aktif_for_web_aktif_veteriners, reverse_set_aktif),
    ]
