# Generated by Django 5.2.4 on 2025-09-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0001_initial'),
        ('veteriner', '0007_siparisistemi_numune_mi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteriner',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinerler', to='anahtarlik.il'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinerler', to='anahtarlik.ilce'),
        ),
    ]
