# Generated by Django 5.2.4 on 2025-09-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0001_initial'),
        ('veteriner', '0008_alter_veteriner_il_alter_veteriner_ilce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisistemi',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siparis_istekleri', to='anahtarlik.il'),
        ),
        migrations.AlterField(
            model_name='siparisistemi',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siparis_istekleri', to='anahtarlik.ilce'),
        ),
    ]
