# Generated by Django 5.2.4 on 2025-09-27 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0002_sahippropaket_sahipproabonelik'),
        ('veteriner', '0009_alter_siparisistemi_il_alter_siparisistemi_ilce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veteriner',
            options={'ordering': ['-olusturulma'], 'verbose_name': 'Veteriner', 'verbose_name_plural': 'Veterinerler'},
        ),
        migrations.AddField(
            model_name='veteriner',
            name='calisma_saatleri',
            field=models.CharField(blank=True, max_length=200, verbose_name='Çalışma Saatleri'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='degerlendirme_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Değerlendirme Sayısı'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='deneyim_yili',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Deneyim Yılı'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='diploma_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Diploma No'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('BEKLEMEDE', 'Beklemede')], default='BEKLEMEDE', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='guncelleme',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='puan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puan'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='uzmanlik_alani',
            field=models.CharField(blank=True, max_length=200, verbose_name='Uzmanlık Alanı'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='ad',
            field=models.CharField(max_length=150, verbose_name='Veteriner Adı'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='adres_detay',
            field=models.TextField(blank=True, verbose_name='Adres Detayı'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinerler', to='anahtarlik.il', verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinerler', to='anahtarlik.ilce', verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='kullanici',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veteriner_profili', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='odeme_modeli',
            field=models.CharField(choices=[('PESIN', 'Peşin Ödeme'), ('KONSINYE', 'Konsinye (Numune) Ödeme')], default='PESIN', max_length=10, verbose_name='Ödeme Modeli'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='satis_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Satış Sayısı'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='tahsis_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Tahsis Sayısı'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='VeterinerBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('ozet', models.TextField(blank=True, max_length=500, verbose_name='Özet')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='veteriner_blog/', verbose_name='Resim')),
                ('yayinda', models.BooleanField(default=False, verbose_name='Yayında')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('yayin_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_yazilari', to='veteriner.veteriner', verbose_name='Veteriner')),
            ],
            options={
                'verbose_name': 'Veteriner Blog',
                'verbose_name_plural': 'Veteriner Blog Yazıları',
                'ordering': ['-yayin_tarihi', '-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='VeterinerHizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmet_adi', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('hizmet_turu', models.CharField(choices=[('MUAYENE', 'Muayene'), ('ASI', 'Aşı'), ('AMELIYAT', 'Ameliyat'), ('YATIS', 'Yatış'), ('ACIL', 'Acil')], max_length=20, verbose_name='Hizmet Türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('sure_dakika', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (Dakika)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizmetler', to='veteriner.veteriner', verbose_name='Veteriner')),
            ],
            options={
                'verbose_name': 'Veteriner Hizmeti',
                'verbose_name_plural': 'Veteriner Hizmetleri',
                'ordering': ['hizmet_adi'],
            },
        ),
        migrations.CreateModel(
            name='VeterinerMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=200, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('cevaplandı', models.BooleanField(default=False, verbose_name='Cevaplandı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veteriner_mesajlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='veteriner.veteriner', verbose_name='Veteriner')),
            ],
            options={
                'verbose_name': 'Veteriner Mesaj',
                'verbose_name_plural': 'Veteriner Mesajları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='VeterinerRandevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randevu_tarihi', models.DateTimeField(verbose_name='Randevu Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('IPTAL', 'İptal'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLEMEDE', max_length=20, verbose_name='Durum')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('evcil_hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='anahtarlik.evcilhayvan', verbose_name='Evcil Hayvan')),
                ('hayvan_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='anahtarlik.sahip', verbose_name='Hayvan Sahibi')),
                ('hizmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='veteriner.veterinerhizmet', verbose_name='Hizmet')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='veteriner.veteriner', verbose_name='Veteriner')),
            ],
            options={
                'verbose_name': 'Veteriner Randevu',
                'verbose_name_plural': 'Veteriner Randevuları',
                'ordering': ['-randevu_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='VeterinerDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puan (1-5)')),
                ('yorum', models.TextField(blank=True, verbose_name='Yorum')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veteriner_degerlendirmeleri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='veteriner.veteriner', verbose_name='Veteriner')),
                ('randevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirme', to='veteriner.veterinerrandevu', verbose_name='Randevu')),
            ],
            options={
                'verbose_name': 'Veteriner Değerlendirme',
                'verbose_name_plural': 'Veteriner Değerlendirmeleri',
                'ordering': ['-olusturulma'],
                'unique_together': {('veteriner', 'kullanici', 'randevu')},
            },
        ),
    ]
