# Generated by Django 5.2.4 on 2025-09-27 20:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0002_sahippropaket_sahipproabonelik'),
        ('veteriner', '0010_alter_veteriner_options_veteriner_calisma_saatleri_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinermesaj',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='veterinermesaj',
            name='veteriner',
        ),
        migrations.RemoveField(
            model_name='veterinerrandevu',
            name='evcil_hayvan',
        ),
        migrations.RemoveField(
            model_name='veterinerrandevu',
            name='hayvan_sahibi',
        ),
        migrations.RemoveField(
            model_name='veterinerrandevu',
            name='hizmet',
        ),
        migrations.RemoveField(
            model_name='veterinerrandevu',
            name='veteriner',
        ),
        migrations.AlterModelOptions(
            name='veteriner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='veterinerdegerlendirme',
            options={'ordering': ['-olusturulma_tarihi'], 'verbose_name': 'Veteriner Değerlendirmesi', 'verbose_name_plural': 'Veteriner Değerlendirmeleri'},
        ),
        migrations.AlterUniqueTogether(
            name='veterinerdegerlendirme',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='deneyim_yili',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='diploma_no',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='guncelleme',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='puan',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='uzmanlik_alani',
        ),
        migrations.RemoveField(
            model_name='veterinerhizmet',
            name='olusturulma',
        ),
        migrations.AddField(
            model_name='veteriner',
            name='acil_hizmet',
            field=models.BooleanField(default=False, help_text='Acil hizmet veriyor mu?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='aylik_satis_hedefi',
            field=models.PositiveIntegerField(default=10, help_text='Aylık satış hedefi'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='bonus_kazanilan',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kazanılan bonus (TL)', max_digits=10),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='evde_hizmet',
            field=models.BooleanField(default=False, help_text='Evde hizmet veriyor mu?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet_verilen_ilceler',
            field=models.TextField(blank=True, help_text='Hizmet verilen ilçeler (virgülle ayırın)'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='ortalama_puan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='seviye',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=20),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='toplam_puan',
            field=models.PositiveIntegerField(default=0, help_text='Toplam performans puanı'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='uzmanlik_alanlari',
            field=models.TextField(blank=True, help_text='Uzmanlık alanları (virgülle ayırın)'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='veterinerdegerlendirme',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veterinerdegerlendirme',
            name='musteri_adi',
            field=models.CharField(default='Anonim', max_length=100),
        ),
        migrations.AddField(
            model_name='veterinerdegerlendirme',
            name='musteri_telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='veterinerdegerlendirme',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinerhizmet',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='ad',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='adres_detay',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='calisma_saatleri',
            field=models.TextField(blank=True, help_text='Çalışma saatleri'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='degerlendirme_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinerler', to='anahtarlik.il'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinerler', to='anahtarlik.ilce'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='kullanici',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veteriner_profili', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='odeme_modeli',
            field=models.CharField(choices=[('PESIN', 'Peşin Ödeme'), ('KONSINYE', 'Konsinye (Numune) Ödeme')], default='PESIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='satis_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='tahsis_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='veterinerdegerlendirme',
            name='puan',
            field=models.PositiveIntegerField(help_text='1-5 arası puan', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='veterinerdegerlendirme',
            name='veteriner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='veteriner.veteriner'),
        ),
        migrations.AlterField(
            model_name='veterinerdegerlendirme',
            name='yorum',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='hizmet_adi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='hizmet_turu',
            field=models.CharField(choices=[('GENEL', 'Genel Muayene'), ('ACIL', 'Acil Müdahale'), ('OPERASYON', 'Operasyon'), ('KONTROL', 'Kontrol Muayenesi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='sure_dakika',
            field=models.PositiveIntegerField(default=30, help_text='Tahmini süre (dakika)'),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='veteriner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizmetler', to='veteriner.veteriner'),
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(max_length=100)),
                ('musteri_telefon', models.CharField(max_length=15)),
                ('musteri_email', models.EmailField(blank=True, max_length=254)),
                ('hayvan_adi', models.CharField(max_length=100)),
                ('hayvan_turu', models.CharField(blank=True, max_length=50)),
                ('hayvan_yasi', models.CharField(blank=True, max_length=20)),
                ('hayvan_cinsiyet', models.CharField(blank=True, max_length=10)),
                ('sorun_aciklamasi', models.TextField(blank=True)),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('durum', models.CharField(choices=[('BEKLENIYOR', 'Bekleniyor'), ('ONAYLANDI', 'Onaylandı'), ('IPTAL', 'İptal'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLENIYOR', max_length=20)),
                ('notlar', models.TextField(blank=True)),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odeme_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ALINDI', 'Alındı'), ('IADE', 'İade Edildi'), ('MUAF', 'Muaf (Numune)')], default='BEKLEMEDE', max_length=20)),
                ('odeme_yontemi', models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('EFT', 'EFT/Havale'), ('KREDI', 'Kredi Kartı'), ('POS', 'Pos/Link'), ('DIGER', 'Diğer')], max_length=10)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, null=True)),
                ('hizmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='veteriner.veterinerhizmet')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='veteriner.veteriner')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-tarih', '-saat'],
                'unique_together': {('veteriner', 'tarih', 'saat')},
            },
        ),
        migrations.AlterField(
            model_name='veterinerdegerlendirme',
            name='randevu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirme', to='veteriner.randevu'),
        ),
        migrations.CreateModel(
            name='VeterinerOdul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odul_turu', models.CharField(help_text='Ödül türü', max_length=50)),
                ('aciklama', models.TextField(help_text='Ödül açıklaması')),
                ('puan', models.PositiveIntegerField(help_text='Kazanılan puan')),
                ('bonus_tutari', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus tutarı (TL)', max_digits=10)),
                ('tarih', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oduller', to='veteriner.veteriner')),
            ],
            options={
                'verbose_name': 'Veteriner Ödül',
                'verbose_name_plural': 'Veteriner Ödülleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.DeleteModel(
            name='VeterinerBlog',
        ),
        migrations.DeleteModel(
            name='VeterinerMesaj',
        ),
        migrations.RemoveField(
            model_name='veterinerdegerlendirme',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='veterinerdegerlendirme',
            name='olusturulma',
        ),
        migrations.DeleteModel(
            name='VeterinerRandevu',
        ),
    ]
