# Generated by Django 5.2.4 on 2025-09-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anahtarlik', '0003_etiket_musteri_adi_etiket_musteri_telefon_and_more'),
        ('veteriner', '0011_remove_veterinermesaj_kullanici_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteriner',
            name='aylik_satis_hedefi',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='bonus_kazanilan',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='seviye',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='toplam_puan',
        ),
        migrations.AlterField(
            model_name='veterinerdegerlendirme',
            name='musteri_adi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinerhizmet',
            name='sure_dakika',
            field=models.PositiveIntegerField(help_text='Tahmini süre (dakika)'),
        ),
        migrations.CreateModel(
            name='VeterinerYuzde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuzde', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Yüzde')),
                ('son_guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veteriner_yuzdeleri', to='anahtarlik.ilce')),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuzde_dagilimlari', to='veteriner.veteriner')),
            ],
            options={
                'verbose_name': 'Veteriner Yüzde Dağılımı',
                'verbose_name_plural': 'Veteriner Yüzde Dağılımları',
                'ordering': ['-yuzde', 'veteriner__ad'],
                'unique_together': {('veteriner', 'ilce')},
            },
        ),
        migrations.DeleteModel(
            name='VeterinerOdul',
        ),
    ]
