# Generated by Django 5.2.4 on 2025-09-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0012_remove_veteriner_aylik_satis_hedefi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='deneyim_yili',
            field=models.PositiveIntegerField(default=0, help_text='Veterinerlik deneyimi (yıl)'),
        ),
    ]
