# Generated by Django 5.2.4 on 2025-09-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0013_veteriner_deneyim_yili'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteriner',
            name='deneyim_yili',
        ),
    ]
