# Generated by Django 5.2.4 on 2025-10-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0014_remove_veteriner_deneyim_yili'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='web_aciklama',
            field=models.TextField(blank=True, help_text='Web sayfası açıklaması'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_aktif',
            field=models.BooleanField(default=False, help_text='Web sayfası aktif mi?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_baslik',
            field=models.CharField(blank=True, help_text='Web sayfası başlığı', max_length=200),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_resim1',
            field=models.ImageField(blank=True, help_text='1. Görsel', null=True, upload_to='veteriner_web/'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_resim2',
            field=models.ImageField(blank=True, help_text='2. Görsel', null=True, upload_to='veteriner_web/'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_resim3',
            field=models.ImageField(blank=True, help_text='3. Görsel', null=True, upload_to='veteriner_web/'),
        ),
    ]
