# Generated by Django 5.2.4 on 2025-10-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0015_veteriner_web_aciklama_veteriner_web_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='hizmet1_aciklama',
            field=models.TextField(blank=True, default='Detaylı fiziksel muayene, teşhis ve sağlık kontrolü.', help_text='1. Hizmet açıklaması'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet1_baslik',
            field=models.CharField(blank=True, default='Genel Muayene', help_text='1. Hizmet başlığı', max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet1_icon',
            field=models.CharField(blank=True, default='🩺', help_text='1. Hizmet ikonu (emoji)', max_length=20),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet2_aciklama',
            field=models.TextField(blank=True, default='Koruyucu aşı programları ve hastalık tedavileri.', help_text='2. Hizmet açıklaması'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet2_baslik',
            field=models.CharField(blank=True, default='Aşılama & Tedavi', help_text='2. Hizmet başlığı', max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet2_icon',
            field=models.CharField(blank=True, default='💉', help_text='2. Hizmet ikonu (emoji)', max_length=20),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet3_aciklama',
            field=models.TextField(blank=True, default='Kan tahlili, röntgen, ultrason gibi teşhis yöntemleri.', help_text='3. Hizmet açıklaması'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet3_baslik',
            field=models.CharField(blank=True, default='Laboratuvar', help_text='3. Hizmet başlığı', max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='hizmet3_icon',
            field=models.CharField(blank=True, default='🔬', help_text='3. Hizmet ikonu (emoji)', max_length=20),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_seo_aciklama',
            field=models.CharField(blank=True, help_text='SEO açıklama (max 160 karakter)', max_length=160),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_seo_anahtar_kelimeler',
            field=models.CharField(blank=True, help_text='SEO anahtar kelimeler (virgülle ayırın)', max_length=255),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_seo_baslik',
            field=models.CharField(blank=True, help_text='SEO başlık (max 70 karakter)', max_length=70),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_slogan',
            field=models.CharField(blank=True, help_text='Alt başlık/slogan (örn: Sevimli Dostlarınız İçin En İyi Bakım)', max_length=300),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='web_slug',
            field=models.SlugField(blank=True, help_text='URL slug (otomatik oluşturulur)', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='web_aciklama',
            field=models.TextField(blank=True, help_text='Hakkımızda metni'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='web_baslik',
            field=models.CharField(blank=True, help_text='Ana başlık (örn: Pati Veteriner Kliniği)', max_length=200),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='web_resim1',
            field=models.ImageField(blank=True, help_text='Ana görsel (Hakkımızda bölümü)', null=True, upload_to='veteriner_web/'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='web_resim2',
            field=models.ImageField(blank=True, help_text='Galeri görseli 1', null=True, upload_to='veteriner_web/'),
        ),
        migrations.AlterField(
            model_name='veteriner',
            name='web_resim3',
            field=models.ImageField(blank=True, help_text='Galeri görseli 2', null=True, upload_to='veteriner_web/'),
        ),
    ]
