# Generated by Django 5.2.4 on 2025-10-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0016_veteriner_hizmet1_aciklama_veteriner_hizmet1_baslik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='carsamba_baslangic',
            field=models.TimeField(blank=True, help_text='Çarşamba başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='carsamba_bitis',
            field=models.TimeField(blank=True, help_text='Çarşamba bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='carsamba_kapali',
            field=models.BooleanField(default=False, help_text='Çarşamba kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cuma_baslangic',
            field=models.TimeField(blank=True, help_text='Cuma başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cuma_bitis',
            field=models.TimeField(blank=True, help_text='Cuma bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cuma_kapali',
            field=models.BooleanField(default=False, help_text='Cuma kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cumartesi_baslangic',
            field=models.TimeField(blank=True, help_text='Cumartesi başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cumartesi_bitis',
            field=models.TimeField(blank=True, help_text='Cumartesi bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cumartesi_kapali',
            field=models.BooleanField(default=False, help_text='Cumartesi kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='pazar_baslangic',
            field=models.TimeField(blank=True, help_text='Pazar başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='pazar_bitis',
            field=models.TimeField(blank=True, help_text='Pazar bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='pazar_kapali',
            field=models.BooleanField(default=True, help_text='Pazar kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='pazartesi_baslangic',
            field=models.TimeField(blank=True, help_text='Pazartesi başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='pazartesi_bitis',
            field=models.TimeField(blank=True, help_text='Pazartesi bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='pazartesi_kapali',
            field=models.BooleanField(default=False, help_text='Pazartesi kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='persembe_baslangic',
            field=models.TimeField(blank=True, help_text='Perşembe başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='persembe_bitis',
            field=models.TimeField(blank=True, help_text='Perşembe bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='persembe_kapali',
            field=models.BooleanField(default=False, help_text='Perşembe kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='sali_baslangic',
            field=models.TimeField(blank=True, help_text='Salı başlangıç saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='sali_bitis',
            field=models.TimeField(blank=True, help_text='Salı bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='sali_kapali',
            field=models.BooleanField(default=False, help_text='Salı kapalı mı?'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
