# Generated by Django 5.2.4 on 2025-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0017_veteriner_carsamba_baslangic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='birincil_renk',
            field=models.CharField(blank=True, help_text='#667eea formatında HEX renk', max_length=7),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cta_link',
            field=models.URLField(blank=True, help_text='Çağrı butonu linki (örn: randevu ya da WhatsApp linki)'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='cta_metin',
            field=models.CharField(blank=True, help_text='Çağrı butonu metni (örn: Randevu Alın)', max_length=50),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='goster_calisma_saatleri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='goster_galeri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='goster_hizmetler',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='goster_sosyal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo', null=True, upload_to='veteriner_web/'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='tema',
            field=models.CharField(blank=True, help_text='Tema adı (örn: default, pastel)', max_length=20),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp numarası (örn: 905551112233)', max_length=20),
        ),
    ]
