# Generated by Django 5.2.4 on 2025-10-20 14:50

from django.db import migrations
from django.utils.text import slugify


def update_slugs_to_ascii(apps, schema_editor):
    """Mevcut Türkçe karakterli slug'ları İngilizce karşılıklarına çevir"""
    Veteriner = apps.get_model('veteriner', 'Veteriner')
    
    # Türkçe karakter dönüşüm tablosu
    tr_map = str.maketrans('çğıöşüÇĞIÖŞÜ', 'cgiosuCGIOSU')
    
    for veteriner in Veteriner.objects.all():
        if veteriner.web_slug:
            # Mevcut slug'u temizle
            temiz_slug = veteriner.web_slug.translate(tr_map)
            base_slug = slugify(temiz_slug, allow_unicode=False)
            
            # Benzersizlik kontrolü
            slug = base_slug
            counter = 1
            while Veteriner.objects.filter(web_slug=slug).exclude(pk=veteriner.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            veteriner.web_slug = slug
            veteriner.save(update_fields=['web_slug'])


def reverse_update_slugs(apps, schema_editor):
    """Geri alma işlemi - slug'ları orijinal isimlere göre yeniden oluştur"""
    Veteriner = apps.get_model('veteriner', 'Veteriner')
    
    for veteriner in Veteriner.objects.all():
        if veteriner.ad:
            base_slug = slugify(veteriner.ad, allow_unicode=True)
            slug = base_slug
            counter = 1
            while Veteriner.objects.filter(web_slug=slug).exclude(pk=veteriner.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            veteriner.web_slug = slug
            veteriner.save(update_fields=['web_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0018_veteriner_birincil_renk_veteriner_cta_link_and_more'),
    ]

    operations = [
        migrations.RunPython(update_slugs_to_ascii, reverse_update_slugs),
    ]
