# Generated by Django 5.2.4 on 2025-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0022_remove_veteriner_boylam_remove_veteriner_enlem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteriner',
            name='konum_koordinat',
        ),
        migrations.AddField(
            model_name='veteriner',
            name='boylam',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Google Maps tipi tam koordinat (ör: 42.428070)', max_digits=12, null=True, verbose_name='Boylam (Longitude)'),
        ),
        migrations.AddField(
            model_name='veteriner',
            name='enlem',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Google Maps tipi tam koordinat (ör: 38.231952)', max_digits=12, null=True, verbose_name='Enlem (Latitude)'),
        ),
    ]
