# Generated by Django 5.2.4 on 2025-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0023_remove_veteriner_konum_koordinat_veteriner_boylam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteriner',
            name='boylam',
        ),
        migrations.RemoveField(
            model_name='veteriner',
            name='enlem',
        ),
        migrations.AddField(
            model_name='veteriner',
            name='konum_koordinat',
            field=models.CharField(blank=True, help_text='Google Maps formatında: 38.231952, 42.428070', max_length=40, null=True, verbose_name='Koordinat'),
        ),
    ]
