# Generated by Django 5.2.4 on 2025-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0024_remove_veteriner_boylam_remove_veteriner_enlem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='musteri_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
