# Generated by Django 5.2.4 on 2025-10-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veteriner', '0025_alter_randevu_musteri_email_alter_randevu_notlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteriner',
            name='ilk_giris_sifre_degistirildi',
            field=models.BooleanField(default=False, help_text='Admin tarafından oluşturulan kullanıcının ilk girişte şifresini değiştirdiğini belirtir.', verbose_name='İlk Giriş Şifre Değiştirildi'),
        ),
    ]
