# Generated by Django 5.2.4 on 2025-09-24 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MisafirProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=15, unique=True)),
                ('uyelik_sozlesmesi_onay', models.BooleanField(default=False)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='misafir_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Misafir Profil',
                'verbose_name_plural': 'Misafir Profilleri',
            },
        ),
    ]
